{
  "hash": "ec0997ee5f588a9ce0869d0e0d884d6b",
  "result": {
    "engine": "knitr",
    "markdown": "---\nengine: knitr\nfilters:\n  - webr\nwebr:\n  show-startup-message: true\n  cell-options:\n    autorun: true\n---\n\n# Shaft, Coupling, and Power Transmission Design\n\n\n\n## Learning Objectives\n\nBy the end of this chapter, you will be able to:\n\n1. **Calculate** the minimum shaft diameter required to transmit a given torque, from an allowable shear stress and a design factor.\n2. **Determine** the diameter increase a keyway forces on an otherwise-adequate shaft, using a torsional stress concentration factor, and **explain** why the alternative — a higher design factor instead of a bigger shaft — is sometimes the better call.\n3. **Select** an appropriate flexible coupling type (jaw, beam, disc, or grid) for a given torque, misalignment, and shock-tolerance requirement, and **justify** the choice against the alternatives.\n4. **Size** a V-belt drive's cross-section and belt quantity from transmitted power, running speed, a service factor, and a wrap-angle correction factor.\n5. **Explain** correct belt tensioning practice and **evaluate** the consequences of over- and under-tensioning on belt life and bearing life.\n6. **Compare** chain and belt drives on torque capacity, slip, contamination, and hygiene compatibility, and **select** the correct one for a stated application and environment.\n7. **Identify** the lubrication/hygiene conflict a chain drive introduces in a washdown or direct-food-contact zone, and **propose** a mitigation.\n\n## Introduction\n\nThe [Motor, Drive, and Gearbox Sizing](06-06-Motor-Drive-Gearbox-Sizing.qmd) chapter finished with a servo motor and a 20:1 planetary gearbox selected for an automotive Tier-1 supplier's rotary index table. That gearbox has an output shaft sticking out of its housing, rated for roughly 40 N·m of continuous output torque. Sizing the motor and gearbox answers \"how much torque and speed does this job need,\" but it does not answer the next question a mechanical designer actually has to solve on the shop floor: **how does that torque physically get from the gearbox's output shaft into the machine it's driving, without the shaft twisting off, the coupling walking apart, or a belt slipping under load?**\n\nThis chapter picks up exactly where that question starts. The same Tier-1 plant, standardizing on a small number of catalog gearmotors to keep its spares crib manageable, uses that identical 40 N·m / 20:1 gearbox on a second machine a few bays over: a short accumulation conveyor feeding parts into the next cell, running at a steady 45 rpm on its head pulley shaft. Between the gearbox's output flange and the conveyor's head pulley sits a length of shaft, a flexible coupling, and — on other machines in the same plant — belt and chain drives doing the same fundamental job under different constraints. Five design tasks build that connection from the shaft outward: sizing the shaft itself against torsional shear, accounting for the strength penalty a keyway introduces, choosing the right coupling architecture, and then stepping outside this specific machine to size belt and chain drives more generally, including when to reach for one over the other.\n\nA note on scope: this chapter is about *sizing the connection hardware* — shaft, coupling, belt, chain — once a torque and speed are already known at both ends. It does not re-derive motor/gearbox sizing (that's [Motor, Drive, and Gearbox Sizing](06-06-Motor-Drive-Gearbox-Sizing.qmd)) or full CEMA-style conveyor belt tension across a belt's whole length (that's the [Conveyor Design](06-10-Conveyor-Design.qmd) chapter later in this part). It also isn't a repeat of the general mechanical-elements coverage of belts, chains, and couplings found earlier in this book — this chapter is narrower and more applied: given a real torque and speed at a real gearbox output flange, what specific shaft, coupling, belt, or chain actually goes in this machine, and why.\n\n## Design Task 1: Shaft Diameter from Torsional Shear Stress\n\n### Scenario\n\nThe mechanical designer on the accumulation-conveyor project has the gearbox's nameplate data in hand: 40 N·m continuous output torque, 45 rpm output speed, delivered through a keyed output shaft stub. Between that stub and the conveyor's head pulley shaft, a short length of intermediate shaft (sometimes called a stub shaft or line shaft) needs to be specified — either a separate machined shaft coupling the two, or, in this case, simply confirming the gearbox's own output shaft stub is adequate to carry a jaw coupling hub without yielding. Either way, the underlying question is the same: **what is the minimum shaft diameter that safely carries 40 N·m, continuously, all shift long?**\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Drivetrain layout between the gearbox output flange and the conveyor head pulley: output shaft, flexible coupling, and head pulley shaft.](06-09-Shaft-Coupling-Power-Transmission_files/figure-pdf/fig-06-09-drivetrain-1.pdf){#fig-06-09-drivetrain fig-align='center'}\n:::\n:::\n\n\n### Design Guidelines and Rules of Thumb\n\nA round shaft transmitting pure torque fails by twisting — the outer fibre of the shaft sees the highest shear stress, and that stress has to stay below a safe fraction of the material's shear strength. \"Safe fraction\" is where the design factor comes in: it absorbs the gap between the idealized calculation and everything the calculation doesn't capture — minor bending nobody accounted for, an occasional torque spike above the nameplate rating, a slightly understrength batch of bar stock, wear over the shaft's service life.\n\nMost shafting is a readily available, inexpensive carbon steel — cold-drawn 1018 or 1045 are common choices — selected for machinability and adequate strength rather than exotic alloy content; a shaft is rarely the highest-stressed component in a drivetrain, and over-specifying its material is a common way to add cost without adding value. Shear yield strength isn't usually published directly for a given steel; the standard estimate, from distortion-energy (von Mises) theory, is $S_{sy} \\approx 0.577\\,S_y$, using the material's tensile yield strength $S_y$, which *is* readily available on a mill certificate or material handbook.\n\n**Rule of thumb:** for a first-pass shaft design with reasonably well-characterized, steady loads, use a design factor $n_d$ in the range 2.5-4 applied to shear yield strength. This breaks down in both directions: for loads measured directly and reliably (e.g., torque feedback from a servo drive's current loop, logged over months of production), a lower $n_d$ around 1.5-2 can be justified with confidence; for poorly-characterized, cyclic, or shock-heavy loads (a shaft that sees genuine impact loading, or millions of reversing cycles over its service life), a static shear-yield calculation like this one isn't the right tool at all — it ignores fatigue entirely, and a proper endurance-limit-based fatigue analysis (Goodman or Soderberg criteria) should replace it.\n\n### Governing Calculation\n\nFor a solid circular shaft in pure torsion, the maximum shear stress occurs at the outer surface:\n\n$$\\tau_{max} = \\frac{16\\,T}{\\pi\\,d^3}$$\n\nSetting the allowable shear stress from material shear yield and design factor, and solving for the minimum diameter:\n\n$$\\tau_{allow} = \\frac{S_{sy}}{n_d} = \\frac{0.577\\,S_y}{n_d} \\qquad\\Rightarrow\\qquad d_{min} = \\left(\\frac{16\\,T\\,n_d}{\\pi\\,S_{sy}}\\right)^{1/3}$$\n\n| Symbol | Description | Unit |\n| :--- | :--- | :--- |\n| $T$ | Transmitted torque | N·m |\n| $d$ | Shaft diameter | m |\n| $S_y$ | Material tensile yield strength | Pa |\n| $S_{sy}$ | Material shear yield strength ($\\approx 0.577\\,S_y$) | Pa |\n| $n_d$ | Design factor | dimensionless |\n| $\\tau_{max}$, $\\tau_{allow}$ | Actual and allowable shear stress | Pa |\n| $d_{min}$ | Minimum required shaft diameter | m |\n\n### Worked Example\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Given: gearbox output torque (from 06-06), and a candidate shafting material\nT <- 40           # N.m, continuous gearbox output torque\nn_d <- 3.0         # design factor, moderate confidence in load/material\nSy <- 370e6        # Pa, cold-drawn 1018 steel tensile yield strength\nSsy <- 0.577 * Sy  # Pa, shear yield estimate (distortion-energy theory)\n\nd_min <- (16 * T * n_d / (pi * Ssy))^(1/3)\nd_min_mm <- d_min * 1000\n\n## Round up to the next standard stock shaft diameter\nd_stock_mm <- 16   # mm, next available metric shafting stock size\ntau_actual <- 16 * T / (pi * (d_stock_mm / 1000)^3)\nn_actual <- Ssy / tau_actual\n\ncat(sprintf(\"Shear yield strength (0.577 x Sy): %.1f MPa\\n\", Ssy / 1e6))\ncat(sprintf(\"Minimum calculated shaft diameter: %.2f mm\\n\", d_min_mm))\ncat(sprintf(\"Selected stock diameter (next size up): %.0f mm\\n\", d_stock_mm))\ncat(sprintf(\"Actual shear stress at %d mm: %.1f MPa\\n\", d_stock_mm, tau_actual / 1e6))\ncat(sprintf(\"Actual design factor achieved: %.2f (target was %.1f)\\n\", n_actual, n_d))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nShear yield strength (0.577 x Sy): 213.5 MPa\nMinimum calculated shaft diameter: 14.20 mm\nSelected stock diameter (next size up): 16 mm\nActual shear stress at 16 mm: 49.7 MPa\nActual design factor achieved: 4.29 (target was 3.0)\n```\n\n\n:::\n:::\n\n\n**Sanity check:** the calculated minimum diameter (14.2 mm) sits comfortably below the 16 mm stock size actually selected, which is exactly what rounding up to a standard size should do — it always adds a little extra margin over the target design factor, here landing at 4.3 rather than the targeted 3.0. That margin isn't wasted: it's about to get spent in Design Task 2, where cutting a keyway into this same 16 mm shaft removes some of it back out again.\n\n## Design Task 2: Keyway Sizing and the Stress Concentration Penalty\n\n### Scenario\n\nA plain 16 mm shaft doesn't connect to anything — torque has to transfer into and out of it somehow, and the shop-standard way to do that on a shaft this size is a keyway: a straight, rectangular slot machined along the shaft, matched by a slot in the coupling hub's bore, with a rectangular key dropped into both to carry the torque as a shear/bearing load rather than relying on an interference fit alone. The designer's problem: that slot is also a stress raiser. The 16 mm shaft sized in Design Task 1 assumed a smooth, notch-free cylinder — cutting a keyway into it means the actual safety factor at the keyway is lower than the 4.3 just calculated, and possibly lower than the 3.0 target.\n\n### Design Guidelines and Rules of Thumb\n\nStandard key sizing is proportional to shaft diameter, not a fixed size: a small instrumentation shaft gets a small key, a large gearbox output shaft gets a proportionally larger one, so that the key's own shear and bearing capacity roughly tracks the shaft's torque capacity as diameter grows. As a rough conceptual guide, square keys in the small-to-medium shaft range commonly run somewhere around one-quarter of the shaft diameter in both width and height, stepping toward a flatter rectangular (wider-than-tall) proportion as shafts get larger. The actual numbers are not a smooth formula — they're published as a stepped table of standard sizes in **ANSI/ASME B17.1** (Keys and Keyseats, inch series) or the metric equivalent **DIN 6885 / ISO 773**, and a real design pulls the key size for a given shaft diameter directly from that table rather than computing it. There is no separate Canadian standard for key and keyseat dimensions; ANSI/ASME B17.1 and the ISO/DIN metric series are used directly in Canadian mechanical design practice, matched to whichever unit system the rest of the machine uses.\n\nCutting that slot into an otherwise round shaft does two things structurally: it removes cross-sectional material (a small effect for a shallow keyway), and — the dominant effect — it creates two sharp internal corners at the base of the slot where stress concentrates sharply, well above the nominal stress the plain-shaft formula predicts. That concentration is captured by a stress concentration factor $K_t$, applied directly to the nominal torsional stress.\n\n**Rule of thumb:** for a first-pass, pure-torque shaft sizing, assume $K_t \\approx 1.6-2.0$ for a standard profiled keyway (values commonly tabulated in stress-concentration references such as Peterson's *Stress Concentration Factors*, based on the fillet radius at the base of the slot — a more generous fillet lowers $K_t$ toward the low end of that range, a sharp-cornered keyway pushes it toward the high end). This breaks down once the same shaft also carries meaningful **bending** — an overhung pulley or sprocket load, for instance, which Design Task 4's belt drive introduces directly onto a shaft. A keyway concentrates bending stress by a similar factor to torsional stress, and a shaft under combined bending and torsion needs a combined-stress equation (not the pure-torsion formula used here) with the stress concentration applied to *both* the bending and torsion terms — treating only the torsional component, as this design task does for a coupling-only connection with negligible bending, would under-predict the required diameter on a shaft that also carries a side load.\n\nThere are two legitimate ways to recover the lost margin: increase the shaft diameter locally at the keyway (the more common shop practice, since it only affects one section of the shaft), or accept the full-length diameter increase and skip a local step, or — less commonly — simply carry a higher design factor everywhere and accept the keyway's stress concentration as already priced in. This chapter works the diameter-increase approach, since it's the one a machinist can act on directly from a drawing.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Shaft cross-section with a standard keyway. The two sharp corners at the base of the slot are where the stress concentration factor applies.](06-09-Shaft-Coupling-Power-Transmission_files/figure-pdf/fig-06-09-keyway-section-1.pdf){#fig-06-09-keyway-section fig-align='center'}\n:::\n:::\n\n\n### Governing Calculation\n\nThe stress concentration factor multiplies the nominal torsional stress directly:\n\n$$\\tau_{max} = K_t\\,\\frac{16\\,T}{\\pi\\,d^3} \\le \\frac{S_{sy}}{n_d}$$\n\nSolving for the diameter required to restore the original target design factor with the keyway in place:\n\n$$d_{keyway} = \\left(\\frac{16\\,T\\,n_d\\,K_t}{\\pi\\,S_{sy}}\\right)^{1/3} = d_{plain}\\times K_t^{1/3}$$\n\n| Symbol | Description | Unit |\n| :--- | :--- | :--- |\n| $K_t$ | Torsional stress concentration factor for the keyway | dimensionless |\n| $d_{plain}$ | Minimum diameter without a keyway (Design Task 1) | m |\n| $d_{keyway}$ | Minimum diameter required with the keyway, at the same $n_d$ | m |\n\n### Worked Example\n\nLive cell — try a sharper or more generous keyway fillet (changing $K_t$) and see how much diameter it costs.\n\n```{webr-r}\n#| label: keyway-upsize-06-09\n## Given (recomputed locally so this cell is self-contained)\nT <- 40; n_d <- 3.0\nSy <- 370e6; Ssy <- 0.577 * Sy\nd_plain <- (16 * T * n_d / (pi * Ssy))^(1/3)   # m, Design Task 1 result\n\nKt <- 1.6   # typical profiled keyway, moderate fillet radius\n\nd_keyway_min <- d_plain * Kt^(1/3)\nd_keyway_min_mm <- d_keyway_min * 1000\n\n## Check: does staying at the original 16 mm stock size (no upsize) still meet n_d?\nd_no_upsize_mm <- 16\ntau_16_with_key <- Kt * 16 * T / (pi * (d_no_upsize_mm / 1000)^3)\nn_16_with_key <- Ssy / tau_16_with_key\n\n## Select the next standard stock size that actually clears d_keyway_min\nd_upsized_mm <- 18\ntau_18_with_key <- Kt * 16 * T / (pi * (d_upsized_mm / 1000)^3)\nn_18_with_key <- Ssy / tau_18_with_key\n\ncat(sprintf(\"Stress concentration factor Kt: %.2f\\n\", Kt))\ncat(sprintf(\"Minimum diameter WITH keyway, same n_d: %.2f mm\\n\", d_keyway_min_mm))\ncat(sprintf(\"If left at 16 mm (no upsize): achieved n_d = %.2f -> %s\\n\",\n            n_16_with_key, ifelse(n_16_with_key >= n_d, \"still OK\", \"BELOW TARGET\")))\ncat(sprintf(\"Upsized to %d mm stock: achieved n_d = %.2f -> %s\\n\",\n            d_upsized_mm, n_18_with_key, ifelse(n_18_with_key >= n_d, \"OK\", \"BELOW TARGET\")))\n```\n\n**Sanity check:** leaving the shaft at 16 mm once the keyway is cut drops the achieved design factor to about 2.7 — below the 3.0 target, even though 16 mm looked comfortable (4.3) before the keyway existed. Stepping up one standard size to 18 mm restores it to about 3.8, with margin to spare. That two-millimetre step is the entire point of this design task: a keyway is not a detail to add after sizing a shaft, it has to be accounted for in the sizing itself, and the fix is usually a small, cheap diameter increase rather than a redesign.\n\n<details>\n<summary>Industry connection: keyway sizing and traceable stock selection</summary>\n\nIn an automotive Tier-1 plant running three shifts, a shaft snapped at a keyway root is exactly the kind of failure a maintenance planner wants to prevent with a documented calculation on file, not discover the hard way during a changeover — a two-millimetre stock upsize is a trivial line-item cost against a shift of downtime waiting on a machined replacement shaft.\n\n</details>\n\n## Design Task 3: Coupling Selection — Jaw, Beam, Disc, and Grid\n\n### Scenario\n\nThe 18 mm shaft is sized. Now it has to actually connect the gearbox's output flange to the conveyor's head pulley shaft, and the two shaft ends will never line up perfectly — a few tenths of a millimetre of parallel offset and a fraction of a degree of angular misalignment are realistic even with careful field alignment using a straightedge and feeler gauges (laser shaft alignment, common on large rotating equipment, is rarely justified for a drive this small). A rigid connection between the two shafts would try to force that misalignment out through bending stress in both shafts and radial load on both sets of bearings, shortening bearing life and risking a fatigue failure. A flexible coupling exists specifically to absorb that misalignment instead of fighting it — but \"flexible coupling\" covers several genuinely different designs, and picking the wrong one either under-protects the machine or spends money on capability this application doesn't need.\n\n### Design Guidelines and Rules of Thumb\n\nFour coupling families cover the large majority of general industrial drives:\n\n- **Jaw couplings** use two metal hubs with interlocking jaws, driving through a soft elastomeric spider trapped between them. The elastomer absorbs shock and modest misalignment, and different spider durometers (hardness) trade off torsional stiffness against vibration damping.\n- **Beam couplings** are a single piece of metal (or occasionally two) with a helical or straight slot pattern machined through it, making the whole coupling flex like a spring. They're inherently zero-backlash but have no separate wear part to absorb shock — the beam itself takes the strain.\n- **Disc couplings** transmit torque through a stack of thin, contoured metal discs bolted alternately to each hub, flexing elastically to absorb misalignment with no elastomer and no working clearance anywhere in the load path.\n- **Grid couplings** use a spring-steel grid that weaves through slots in two facing hubs, covered by a lubricated housing — mechanically similar in spirit to a jaw coupling's shock-absorbing role, but built for much higher torque and a harsher duty.\n\n\n::: {#tbl-06-09-coupling-selection .cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{llllll}\n\\caption{\\label{tab:tbl-06-09-coupling-selection}Flexible coupling selection guide (representative, illustrative values)}\\\\\n\\toprule\n\\cellcolor[HTML]{4a86c7}{\\textcolor{white}{\\textbf{Type}}} & \\cellcolor[HTML]{4a86c7}{\\textcolor{white}{\\textbf{Torque Capacity}}} & \\cellcolor[HTML]{4a86c7}{\\textcolor{white}{\\textbf{Misalignment (Ang. / Par. / Axial)}}} & \\cellcolor[HTML]{4a86c7}{\\textcolor{white}{\\textbf{Backlash}}} & \\cellcolor[HTML]{4a86c7}{\\textcolor{white}{\\textbf{Shock Tolerance}}} & \\cellcolor[HTML]{4a86c7}{\\textcolor{white}{\\textbf{Typical Use}}}\\\\\n\\midrule\nJaw (elastomeric spider) & Low - moderate (small drives up to a few hundred N·m) & \\textasciitilde{}1° / moderate / some float & Low - zero (preloaded spider) & Good (elastomer absorbs shock) & General-purpose motor/gearbox drives, pumps, conveyors\\\\\nBeam & Low (light-duty, precision motion control) & \\textasciitilde{}0.5-1° / small / some float & Zero (monolithic flexure) & Poor (no separate wear part; beam itself can fatigue/fracture) & Encoders, steppers, precision servo feedback, instrumentation\\\\\nDisc (metal disc pack) & Moderate - high (up to several thousand N·m in larger sizes) & \\textasciitilde{}0.5-1° / limited (needs a spacer) / good with spacer & Zero (all-metal flexure) & Moderate - good & Precision high-torque servo/spindle drives needing zero backlash\\\\\nGrid & High - very high (large industrial equipment) & \\textasciitilde{}0.5-1° / moderate / good float & Some (working clearance in the grid) & Excellent (purpose-built for shock/vibration) & Heavy industrial rotating equipment: large pumps, fans, compressors\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Illustrative comparison of the four coupling families across four selection criteria. Higher is better in each case.](06-09-Shaft-Coupling-Power-Transmission_files/figure-pdf/fig-06-09-coupling-compare-1.pdf){#fig-06-09-coupling-compare fig-align='center'}\n:::\n:::\n\n\n**Rule of thumb:** default to the simplest, cheapest coupling family that meets the drive's torque, misalignment, and shock requirements with reasonable margin — for the large majority of general industrial drives below a few hundred N·m, that's a jaw coupling. This breaks down for precision motion control (encoder feedback couplings, small stepper/servo shafts) where a beam coupling's zero backlash and low added inertia matter more than shock tolerance, and for large, continuously running, shock-loaded industrial equipment (big pumps, fans, compressors) where a grid coupling's shock tolerance and torque capacity justify its extra cost and the periodic lubrication its housing needs.\n\nBore and keyway dimensions on catalog couplings are themselves standardized — **AGMA 9002** (Bores and Keyways for Flexible Couplings) is the relevant North American reference, ensuring a given catalog coupling bore actually matches the shaft and key sized in Design Tasks 1 and 2 without a custom bore. There is no separate Canadian standard for coupling bore/keyway sizing; AGMA 9002 is used directly.\n\n### Governing Calculation\n\nThere's no single closed-form equation here — coupling selection is a judgment call across several qualitative and quantitative criteria at once — but a **weighted decision matrix** turns that judgment call into a documented, repeatable process, the same tool used for the servo-vs-induction-motor decision in [Motor, Drive, and Gearbox Sizing](06-06-Motor-Drive-Gearbox-Sizing.qmd):\n\n$$Score_{option} = \\sum_i w_i \\times s_{i,option}$$\n\n| Symbol | Description | Unit |\n| :--- | :--- | :--- |\n| $w_i$ | Weight assigned to criterion $i$ (weights sum to 1.0) | dimensionless |\n| $s_{i,option}$ | Score of a given coupling family against criterion $i$ (1-5 scale) | dimensionless |\n| $Score_{option}$ | Total weighted score for that coupling family | dimensionless |\n\n### Worked Example\n\nLive cell — try different weights (what matters most on *your* drive?) and see whether the recommendation changes.\n\n```{webr-r}\n#| label: coupling-decision-06-09\n## Given: weights reflecting the accumulation conveyor's priorities\nweights <- c(torque_margin = 0.20, misalignment = 0.25, shock = 0.30, cost_maintenance = 0.25)\n\njaw_scores  <- c(torque_margin = 4, misalignment = 4, shock = 5, cost_maintenance = 5)\nbeam_scores <- c(torque_margin = 3, misalignment = 3, shock = 2, cost_maintenance = 4)\ndisc_scores <- c(torque_margin = 5, misalignment = 3, shock = 4, cost_maintenance = 2)\ngrid_scores <- c(torque_margin = 5, misalignment = 4, shock = 5, cost_maintenance = 2)\n\nscores_list <- list(Jaw = jaw_scores, Beam = beam_scores, Disc = disc_scores, Grid = grid_scores)\ntotals <- sapply(scores_list, function(s) sum(weights * s))\n\ncat(\"Weighted decision matrix (1 = poor fit, 5 = excellent fit):\\n\\n\")\nfor (nm in names(weights)) cat(sprintf(\"  %-18s weight = %.0f%%\\n\", nm, weights[nm] * 100))\ncat(\"\\n\")\nfor (nm in names(totals)) cat(sprintf(\"  %-6s weighted score = %.2f\\n\", nm, totals[nm]))\ncat(sprintf(\"\\n-> Recommendation: %s coupling\\n\", names(totals)[which.max(totals)]))\n```\n\n**Sanity check:** the jaw coupling wins (4.55) ahead of the grid coupling (4.00), even though the comparison chart shows grid scoring at least as well on every individual criterion except cost/maintenance. That's the point of the exercise — at this torque level (a few tens of N·m), a grid coupling's extra torque and shock capacity is capability this drive will never use, while its lubricated housing adds a maintenance task the jaw coupling simply doesn't have. Try raising the shock weight further, toward a jam-prone, high-impact application: the recommendation shifts back toward grid, exactly the crossover a real selection decision has to navigate.\n\n## Design Task 4: Belt Drive Design\n\n### Scenario\n\nA different machine in the same plant — a scrap-chip conveyor pulling steel turnings away from a CNC line — uses a V-belt drive instead of a direct-coupled shaft: a 5 hp (3.7 kW), 1750 rpm motor drives the conveyor's head shaft down to 350 rpm through a pair of V-belt sheaves, a 5:1 speed reduction. V-belts are a common choice for exactly this kind of drive — a meaningful speed reduction, moderate power, some tolerance for shaft misalignment and installation imprecision that a direct coupling wouldn't forgive, and the shock-absorbing/overload-slipping behaviour of a friction drive as a bonus safety margin against a jam. The designer's job: how many belts, of what cross-section, does this drive actually need?\n\n### Design Guidelines and Rules of Thumb\n\nA V-belt's rated power capacity, published in the belt manufacturer's power-rating tables, is a function of the belt's cross-section (a wider, deeper belt carries more power), the *small* sheave's diameter (a belt bent around a smaller radius sees more internal flexing stress, which lowers its rated power at a given speed), and the belt's running speed. Those tables are proprietary to each manufacturer and are not reproduced here — an actual design pulls the rated power for the specific belt section, sheave diameter, and speed directly from the manufacturer's current catalog — but the table below gives representative, illustrative magnitudes so the scale of the numbers involved is clear.\n\n\n::: {#tbl-06-09-belt-ratings .cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{llll}\n\\caption{\\label{tab:tbl-06-09-belt-ratings}Illustrative V-belt cross-section power ranges (representative magnitudes, not a manufacturer catalog)}\\\\\n\\toprule\n\\cellcolor[HTML]{4a86c7}{\\textcolor{white}{\\textbf{Section}}} & \\cellcolor[HTML]{4a86c7}{\\textcolor{white}{\\textbf{Approx. Top Width}}} & \\cellcolor[HTML]{4a86c7}{\\textcolor{white}{\\textbf{Typical Power Range per Belt}}} & \\cellcolor[HTML]{4a86c7}{\\textcolor{white}{\\textbf{Typical Application}}}\\\\\n\\midrule\nZ / 3V (narrow) & \\textasciitilde{}10 mm & 0.4 - 2 kW & Small fractional-hp drives, fans, small pumps\\\\\nA / SPA & \\textasciitilde{}13 mm & 1 - 4 kW & General-purpose light industrial drives\\\\\nB / SPB & \\textasciitilde{}17 mm & 2 - 7 kW & Medium industrial drives, compressors, conveyors\\\\\nC / SPC & \\textasciitilde{}22 mm & 5 - 15 kW & Heavy industrial drives, large fans/compressors\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\nThe catalog rated power assumes a full, or near-full, 180° wrap around the *small* sheave — which only happens when both sheaves are nearly the same diameter. A speed-reducing drive like this one, with a large ratio between sheaves and a relatively short center distance, wraps distinctly less than 180° around the small sheave, and the belt's actual usable capacity drops accordingly. Manufacturers publish a wrap-angle (arc of contact) correction factor for exactly this reason, applied as a simple multiplier on the rated power.\n\n\n::: {#tbl-06-09-wrap-correction .cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{rr}\n\\caption{\\label{tab:tbl-06-09-wrap-correction}Illustrative wrap-angle correction factor (representative values, not a manufacturer catalog)}\\\\\n\\toprule\n\\cellcolor[HTML]{4a86c7}{\\textcolor{white}{\\textbf{Wrap Angle (deg)}}} & \\cellcolor[HTML]{4a86c7}{\\textcolor{white}{\\textbf{Correction Factor C\\_theta}}}\\\\\n\\midrule\n180 & 1.00\\\\\n160 & 0.95\\\\\n140 & 0.89\\\\\n120 & 0.82\\\\\n100 & 0.74\\\\\n\\addlinespace\n90 & 0.69\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\nThere is no separate Canadian standard governing V-belt drive design; the relevant engineering practice is published by **ARPM** (Association for Rubber Products Manufacturers, formerly the Rubber Manufacturers Association, RMA) in North America, cross-referenced internationally against **ISO 5292** for belt drive capacity ratings — both used directly in Canadian mechanical design practice.\n\n**Rule of thumb:** size belt drives from the manufacturer's rated power table *and* the wrap-angle correction together — never rated power alone. A high-ratio, short-center-distance drive like this one can lose 15-30% of a belt's nominal capacity to wrap angle alone, and skipping that correction is a common way to end up with an undersized belt drive that looks adequate on paper. This breaks down for near-1:1 ratio drives (both sheaves close in diameter, wrap angle on each close to 180°), where the correction factor is close enough to 1.0 that a first-pass estimate can reasonably skip it.\n\nBecause exposed belts and sheaves are a serious pinch-point and entanglement hazard, any belt drive accessible to a worker during normal operation needs a fixed guard — required in Ontario under the **Occupational Health and Safety Act** and **O. Reg. 851** (Industrial Establishments), with **CSA Z432** (Safeguarding of Machinery) as the relevant design standard; the international/US equivalent is OSHA's machine guarding requirements under **29 CFR 1910.219**.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Belt drive geometry for the 5:1 scrap-conveyor drive: a 100 mm driver sheave and a 500 mm driven sheave, 600 mm center distance. The driver sheave's wrap angle (highlighted) is noticeably less than 180 degrees.](06-09-Shaft-Coupling-Power-Transmission_files/figure-pdf/fig-06-09-belt-sheave-geometry-1.pdf){#fig-06-09-belt-sheave-geometry fig-align='center'}\n:::\n:::\n\n\nOnce a belt drive is installed, correct **tensioning** matters as much as correct sizing: a belt that's too loose slips under load (wasting power as heat and wearing the belt's sidewalls prematurely) and whips, while a belt that's too tight overloads both shafts' bearings with unnecessary radial force, shortening bearing life without adding any transmittable power once the belt is no longer slipping.\n\n**Rule of thumb:** tension a V-belt so that it deflects a small, specified amount (often quoted as roughly 1/64 inch of deflection per inch of belt span) under a specified force, checked at the midpoint of the span, per the belt manufacturer's deflection-force chart for that belt's cross-section — not by feel, and not by \"as tight as it'll go.\" This breaks down for synchronous (toothed) belts, which transmit power through tooth engagement rather than friction and are tensioned to a much lower, specified static tension; over-tightening a toothed belt buys no power-transmission benefit and only stresses the belt and bearings.\n\n### Governing Calculation\n\nSheave ratio, from either diameter or speed:\n\n$$i = \\frac{D_{driven}}{D_{driver}} = \\frac{n_{driver}}{n_{driven}}$$\n\nWrap angle at the small (driver) sheave, from sheave diameters and center distance $C$:\n\n$$\\theta_{wrap} = 180° - 2\\sin^{-1}\\left(\\frac{D_{driven} - D_{driver}}{2\\,C}\\right)$$\n\nDesign power, applying a service factor for shock/duty, and the number of belts required:\n\n$$P_{design} = P_{transmitted} \\times SF \\qquad N_{belts} = \\left\\lceil \\frac{P_{design}}{P_{rated}\\times C_\\theta} \\right\\rceil$$\n\n| Symbol | Description | Unit |\n| :--- | :--- | :--- |\n| $D_{driver}$, $D_{driven}$ | Driver (small) and driven (large) sheave pitch diameters | mm |\n| $C$ | Center distance between sheave shafts | mm |\n| $\\theta_{wrap}$ | Wrap (arc of contact) angle at the driver sheave | degrees |\n| $P_{transmitted}$ | Power to be transmitted | kW |\n| $SF$ | Service factor (shock, duty cycle) | dimensionless |\n| $P_{rated}$ | Manufacturer's rated power per belt, at this section/diameter/speed | kW |\n| $C_\\theta$ | Wrap-angle correction factor | dimensionless |\n| $N_{belts}$ | Number of belts required (rounded up) | dimensionless |\n\n### Worked Example\n\nLive cell — try a different motor size, sheave ratio, or center distance and see how the belt count responds.\n\n```{webr-r}\n#| label: belt-sizing-06-09\n## Given\nP_motor_hp <- 5\nP_transmitted <- P_motor_hp * 0.746   # kW\nn_motor <- 1750                        # rpm\nD_driver <- 100; D_driven <- 500       # mm\nC <- 600                                # mm, center distance\nSF <- 1.4                               # moderate shock: chip conveyor, occasional jams\n\nratio <- D_driven / D_driver\nn_driven <- n_motor / ratio\n\ntheta_wrap <- 180 - 2 * asin((D_driven - D_driver) / (2 * C)) * 180 / pi\n\n## Representative wrap-angle correction table, interpolated\nwrap_tab <- data.frame(theta = c(90, 100, 110, 120, 130, 140, 150, 160, 170, 180),\n                        C_theta = c(0.69, 0.74, 0.78, 0.82, 0.86, 0.89, 0.92, 0.95, 0.97, 1.00))\nC_theta <- approx(wrap_tab$theta, wrap_tab$C_theta, xout = theta_wrap)$y\n\nP_design <- P_transmitted * SF\nP_rated_per_belt <- 3.0   # kW, representative B-section rating at this diameter/speed\n\nN_belts_exact <- P_design / (P_rated_per_belt * C_theta)\nN_belts <- ceiling(N_belts_exact)\n\ncat(sprintf(\"Sheave ratio: %.1f:1 -> driven-shaft speed: %.0f rpm\\n\", ratio, n_driven))\ncat(sprintf(\"Transmitted power: %.2f kW, design power (SF = %.1f): %.2f kW\\n\",\n            P_transmitted, SF, P_design))\ncat(sprintf(\"Wrap angle at driver sheave: %.1f deg -> C_theta = %.2f\\n\", theta_wrap, C_theta))\ncat(sprintf(\"Belts required (exact): %.2f -> select %d belts\\n\", N_belts_exact, N_belts))\n```\n\n**Sanity check:** the exact belt count (1.94) rounds up to 2 — a single belt would be running at 97% of its wrap-angle-corrected capacity with zero margin for the jam shock the service factor was supposed to cover, so rounding down would defeat the purpose of applying a service factor in the first place. Note the wrap-angle correction alone knocked more than 10% off the belt's nominal rating (C_theta = 0.89) before the service factor was even applied — exactly the effect the rule of thumb above warns not to skip on a high-ratio drive like this one.\n\n## Design Task 5: Chain Drive Basics and Chain vs. Belt Selection\n\n### Scenario\n\nA food processing plant runs a dough-handling line: an auger conveyor moves proofed dough from a mixer into a divider at low speed and high, occasionally shock-loaded torque — dough is dense, and an auger jam is a real, regular event, not a rare edge case. Two bays downstream, past the oven, a second conveyor moves already-baked, individually wrapped product toward a case packer at a modest, steady torque with far less shock. Both conveyors need a positive, reliable drive between a gearmotor and a driven shaft — but the auger conveyor sits in the plant's primary, direct-product-contact washdown zone (CFIA-regulated, hosed down with hot water and sanitizer between shifts), while the case-packer conveyor, handling already-wrapped product, is in a lower-hygiene-risk secondary zone. Should either of these use a chain drive instead of a belt — and does the answer change between the two zones?\n\n### Design Guidelines and Rules of Thumb\n\nA chain drive transmits torque through positive mechanical engagement — hardened steel rollers seated in the teeth of a sprocket — rather than friction, which gives it two properties a belt fundamentally cannot match: **zero slip** (the driven shaft's speed is locked to the driver's by the chain's pitch and the sprocket tooth count, with no creep over time the way a friction belt very slightly stretches and slips under load) and substantially higher torque capacity for a given size, because it isn't relying on friction against a smooth surface to transmit load. That makes chain the natural choice for high-torque, low-speed, positive-drive applications — augers, positive-displacement pumps, indexing conveyors that need to stay in exact mechanical sync over long runs — exactly the auger conveyor's profile.\n\nThe relevant standard is **ANSI/ASA B29.1** (Precision Power Transmission Roller Chains, Attachments, and Sprockets) in North America, cross-referenced internationally against **ISO 606** (short-pitch transmission precision roller chains and chain wheels); there is no separate Canadian chain-drive design standard, and both are used directly in Canadian practice.\n\nChain's real cost is what belts don't need at all: **lubrication.** Every pin-and-bushing joint in a roller chain needs oil (or grease, for slower/heavier chains) to control wear between the pin and bushing as the chain articulates around the sprockets; run a standard chain dry and it wears rapidly, stretches, and eventually skips teeth or fails outright. That's a direct conflict with a washdown, direct-product-contact food zone: an open, oil-lubricated chain is both a contamination risk (lubricant migrating onto product or the surrounding surfaces) and something that gets aggressively hosed clean of its own lubricant every shift, right when it needs that lubricant to survive. A well-sealed, lubrication-free belt has no equivalent problem — nothing on it needs periodic oiling, and washdown water and sanitizer don't strip away anything the drive depends on.\n\n\n::: {#tbl-06-09-chain-belt .cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{lll}\n\\caption{\\label{tab:tbl-06-09-chain-belt}Chain vs. belt drive comparison for a food-processing washdown context}\\\\\n\\toprule\n\\cellcolor[HTML]{4a86c7}{\\textcolor{white}{\\textbf{Criterion}}} & \\cellcolor[HTML]{4a86c7}{\\textcolor{white}{\\textbf{Chain Drive}}} & \\cellcolor[HTML]{4a86c7}{\\textcolor{white}{\\textbf{Belt Drive}}}\\\\\n\\midrule\nTorque capacity (given size) & High & Low - moderate (friction-limited)\\\\\nSlip / speed precision & None (positive engagement) & Slight creep under load (V-belt); near-zero for synchronous belts\\\\\nContamination risk & Lubricant can migrate onto product/surfaces & Minimal (no lubricant needed)\\\\\nWashdown / hygiene compatibility & Poor unless self-lubricating/enclosed washdown chain used & Good — sealed, wash-down-rated belts are common\\\\\nMaintenance & Periodic lubrication and wear inspection required & Periodic tension check; no lubrication\\\\\n\\addlinespace\nTypical cost & Often lower for the torque delivered & Often higher for equivalent torque capacity\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Illustrative comparison of chain and belt drives across five decision criteria for a food-processing context. Higher is better in each case.](06-09-Shaft-Coupling-Power-Transmission_files/figure-pdf/fig-06-09-chain-belt-compare-1.pdf){#fig-06-09-chain-belt-compare fig-align='center'}\n:::\n:::\n\n\n**Rule of thumb:** chain generally beats belt whenever a drive needs high torque at low speed with zero slip and no long-term ratio drift — augers, positive-displacement pumps, and exactly-synchronized indexing conveyors are the classic cases. This breaks down hard in a washdown or direct-food-contact zone: chain's own lubrication requirement can erase the advantage entirely unless a **self-lubricating** (oil-impregnated bushing) or **dry-film-lubricated stainless washdown chain** is specified, fully enclosed in a lubricant-tight guard to keep both wash water out and any residual lubricant in — and even then, periodic inspection and re-lubrication remain a real maintenance burden a sealed, lubrication-free belt simply doesn't carry. Don't default to chain on torque capacity alone without checking whether the environment can actually support what chain needs to survive in it.\n\n### Governing Calculation\n\nLike the coupling decision in Design Task 3, chain-vs-belt is a multi-criteria judgment call rather than a single formula — the same weighted decision matrix applies, scored against criteria that matter for the specific zone in question:\n\n$$Score_{option} = \\sum_i w_i \\times s_{i,option}$$\n\n| Symbol | Description | Unit |\n| :--- | :--- | :--- |\n| $w_i$ | Weight assigned to criterion $i$ for this zone (weights sum to 1.0) | dimensionless |\n| $s_{i,option}$ | Score of chain or belt against criterion $i$ (1-5 scale) | dimensionless |\n| $Score_{option}$ | Total weighted score for that drive type | dimensionless |\n\n### Worked Example\n\nLive cell — try re-weighting the criteria for your own plant's zone classification and see whether the recommendation flips.\n\n```{webr-r}\n#| label: chain-belt-decision-06-09\n## Scores (1 = poor fit, 5 = excellent fit), standard (non-washdown) chain assumed\nchain_scores <- c(torque = 5, no_slip = 5, hygiene = 1, maintenance = 2, cost = 4)\nbelt_scores  <- c(torque = 3, no_slip = 4, hygiene = 5, maintenance = 5, cost = 3)\n\n## Zone A: primary, direct-product-contact washdown zone (auger conveyor)\nweights_A <- c(torque = 0.15, no_slip = 0.15, hygiene = 0.40, maintenance = 0.20, cost = 0.10)\n## Zone B: secondary, packaged-product zone, high torque matters more (case conveyor)\nweights_B <- c(torque = 0.30, no_slip = 0.20, hygiene = 0.10, maintenance = 0.15, cost = 0.25)\n\nscore_zone <- function(weights) {\n  c(Chain = sum(weights * chain_scores), Belt = sum(weights * belt_scores))\n}\n\nzoneA <- score_zone(weights_A)\nzoneB <- score_zone(weights_B)\n\ncat(\"Zone A - primary washdown, direct product contact (auger conveyor):\\n\")\ncat(sprintf(\"  Chain weighted score: %.2f\\n\", zoneA[\"Chain\"]))\ncat(sprintf(\"  Belt weighted score:  %.2f\\n\", zoneA[\"Belt\"]))\ncat(sprintf(\"  -> Recommendation: %s\\n\\n\", names(zoneA)[which.max(zoneA)]))\n\ncat(\"Zone B - secondary, packaged-product zone (case conveyor):\\n\")\ncat(sprintf(\"  Chain weighted score: %.2f\\n\", zoneB[\"Chain\"]))\ncat(sprintf(\"  Belt weighted score:  %.2f\\n\", zoneB[\"Belt\"]))\ncat(sprintf(\"  -> Recommendation: %s\\n\", names(zoneB)[which.max(zoneB)]))\n```\n\n**Sanity check:** the recommendation flips between the two zones (belt wins Zone A 4.35 to 2.70; chain wins Zone B 3.90 to 3.70), which is the whole point of scoring the *same* two drive types against *different* zone priorities rather than picking one winner for the whole plant. Zone B's result is close — a 0.20-point margin — which correctly signals a genuine trade-off rather than an obvious call; specifying a self-lubricating washdown chain there (raising its hygiene score from 1 toward 3) would likely tip it further toward chain, while a shock-loaded, hygiene-critical zone like the auger conveyor isn't close at all.\n\n<details>\n<summary>Industry connection: the lubrication nuance in a CFIA-regulated plant</summary>\n\nA standard oil-lubricated chain on the auger conveyor would fail a CFIA (Canadian Food Inspection Agency) sanitary design review outright — lubricant in a direct-product-contact zone is exactly the kind of finding that stops a plant audit cold. The fix isn't automatically \"use a belt everywhere\"; it's recognizing that chain's torque and no-slip advantages sometimes still win once a self-lubricating or dry-film-lubricated stainless washdown chain, fully guarded, is priced against a belt's own limitations at that torque level — the decision matrix above is how that trade-off gets documented, not guessed at.\n\n</details>\n\n## Summary\n\n\n::: {#tbl-06-09-summary .cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{lll}\n\\caption{\\label{tab:tbl-06-09-summary}Design task summary: governing equations and key rules of thumb}\\\\\n\\toprule\n\\cellcolor[HTML]{4a86c7}{\\textcolor{white}{\\textbf{Design Task}}} & \\cellcolor[HTML]{4a86c7}{\\textcolor{white}{\\textbf{Governing Equation}}} & \\cellcolor[HTML]{4a86c7}{\\textcolor{white}{\\textbf{Key Rule of Thumb}}}\\\\\n\\midrule\n1. Shaft diameter (torsion) & \\$d\\_\\{min\\} = \\textbackslash{}left(\\textbackslash{}dfrac\\{16Tn\\_d\\}\\{\\textbackslash{}pi S\\_\\{sy\\}\\}\\textbackslash{}right)\\textasciicircum{}\\{1/3\\}\\$ & Design factor \\$n\\_d \\textbackslash{}approx 2.5-4\\$ for well-characterized static loads\\\\\n2. Keyway stress concentration & \\$d\\_\\{keyway\\} = d\\_\\{plain\\}\\textbackslash{}times K\\_t\\textasciicircum{}\\{1/3\\}\\$ & \\$K\\_t \\textbackslash{}approx 1.6-2.0\\$ for a standard keyway in torsion\\\\\n3. Coupling selection & \\$Score = \\textbackslash{}sum\\_i w\\_i s\\_\\{i,option\\}\\$ & Default to jaw couplings unless precision or heavy shock demands otherwise\\\\\n4. Belt drive sizing & \\$N\\_\\{belts\\} = \\textbackslash{}lceil P\\_\\{design\\}/(P\\_\\{rated\\}C\\_\\textbackslash{}theta)\\textbackslash{}rceil\\$ & Always apply the wrap-angle correction on high-ratio drives, not rated power alone\\\\\n5. Chain vs. belt & \\$Score = \\textbackslash{}sum\\_i w\\_i s\\_\\{i,option\\}\\$ & Chain wins on torque/no-slip; its lubrication need can lose that in a washdown zone\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n## Practice Problems\n\n<details>\n<summary>Design Task 1 (plug-in): shaft diameter for a different torque</summary>\n\nA gearmotor delivers 65 N·m continuous torque. Using the same 1018 CD steel ($S_y = 370$ MPa) and a design factor of $n_d = 3.0$, what is the minimum shaft diameter?\n\n**Answer:** $d_{min} = \\left(\\dfrac{16 \\times 65 \\times 3.0}{\\pi \\times 213.5\\times10^6}\\right)^{1/3} = 0.01669\\ \\text{m} \\approx 16.7\\ \\text{mm}$. Round up to the next standard stock size, 18 mm.\n\n</details>\n\n<details>\n<summary>Design Task 1 (design decision): raising the design factor vs. changing material</summary>\n\nA vendor quotes two options for a shaft that must carry 40 N·m: (a) 16 mm diameter in 1018 CD steel ($S_y = 370$ MPa), or (b) 14 mm diameter in a higher-strength alloy steel ($S_y = 700$ MPa), both claiming the same design factor. Which would you choose, and what would make you hesitate about option (b)?\n\n**Answer:** Option (b) checks out on paper — $S_{sy}$ scales with $S_y$, so a smaller diameter can hit the same $n_d$ against shear yield. The hesitation: a smaller-diameter shaft is *more* sensitive to the same absolute keyway depth (the keyway removes a larger fraction of a smaller shaft's cross-section and the stress concentration factor is applied to a smaller base stress capacity margin), it's stiffer to source and machine as a special order versus common 1018 stock, and alloy steel buys strength this application doesn't obviously need — a shaft is rarely the limiting component in a drivetrain, so paying for exotic material to shrink it further is often solving a problem (space) that doesn't exist here. Choose (a) unless there's a genuine space constraint driving the decision.\n\n</details>\n\n<details>\n<summary>Design Task 2 (plug-in): required diameter with a sharper keyway fillet</summary>\n\nUsing the 40 N·m / $n_d = 3.0$ / 1018 steel shaft from this chapter's worked example, what minimum diameter is required if the keyway is cut with a sharp corner ($K_t = 2.0$) instead of the standard rounded fillet ($K_t = 1.6$)?\n\n**Answer:** $d_{plain} = 14.2$ mm (Design Task 1 result). $d_{keyway} = 14.2 \\times 2.0^{1/3} = 14.2 \\times 1.260 \\approx 17.9$ mm — round up to 18 mm, the same stock size as the $K_t = 1.6$ case, but with noticeably less margin. Below 18 mm, the sharp-cornered keyway would fail the target design factor where the rounded one still passed.\n\n</details>\n\n<details>\n<summary>Design Task 2 (design decision): local upsize vs. full-length upsize</summary>\n\nA shaft needs to be 18 mm at the keyway but only 16 mm everywhere else it's supported by bearings sized for 16 mm bore. Would you machine a local step up to 18 mm just at the keyway, or make the whole shaft 18 mm and re-select the bearings?\n\n**Answer:** A local step (a short 18 mm section at the keyway, stepping back down to 16 mm at the bearing journals) is almost always the better call for an existing bearing selection — it solves the actual stress concentration exactly where it occurs, adds one extra machining operation (a shoulder), and doesn't force a bearing re-selection or a wider housing bore. Making the whole shaft 18 mm only makes sense if the bearings weren't selected yet, or if a single constant diameter meaningfully simplifies stocking spare shafts — worth it in a plant that stocks a lot of spares, not worth it as a default.\n\n</details>\n\n<details>\n<summary>Design Task 3 (plug-in): scoring a beam coupling against a precision servo application</summary>\n\nFor an encoder-feedback coupling on a servo motor (low torque, needs zero backlash, minimal shock expected), score a beam coupling and a jaw coupling using weights: misalignment = 0.20, shock = 0.10, cost/maintenance = 0.20, and a new criterion, backlash = 0.50 (beam = 5, jaw = 3 on backlash; reuse this chapter's other scores for the remaining criteria). Which wins?\n\n**Answer:** Beam: $0.20(3) + 0.10(2) + 0.20(4) + 0.50(5) = 0.6+0.2+0.8+2.5 = 4.1$. Jaw: $0.20(4)+0.10(5)+0.20(5)+0.50(3) = 0.8+0.5+1.0+1.5 = 3.8$. Beam wins (4.1 vs 3.8) once backlash is weighted this heavily — exactly the precision-motion-control case where the chapter's rule of thumb says beam couplings earn their place despite scoring poorly on shock tolerance.\n\n</details>\n\n<details>\n<summary>Design Task 3 (design decision): coupling choice for a reversing, jam-prone auger</summary>\n\nThe dough auger from Design Task 5 occasionally jams hard enough to stall the motor, and the drive needs to survive that event repeatedly without a coupling failure. Which coupling family from this chapter's table would you specify, and why would you rule out a beam coupling specifically?\n\n**Answer:** A grid coupling — its spring-steel grid is purpose-built for exactly this kind of repeated shock/overload event, and its higher torque capacity gives margin against a hard stall. A beam coupling is specifically the wrong choice here: it has no separate wear part to absorb shock, so a hard stall transmits directly into the beam's flexure geometry, risking a fatigue crack or outright fracture at the slots — a beam coupling is built for smooth, low-shock precision motion, the opposite of this application's duty.\n\n</details>\n\n<details>\n<summary>Design Task 4 (plug-in): belt count for a smaller motor</summary>\n\nA 2 hp (1.49 kW) motor drives the same 5:1, 600 mm center-distance sheave arrangement as this chapter's worked example, with the same SF = 1.4 and the same B-section belt rated at 3.0 kW. How many belts are required?\n\n**Answer:** $P_{design} = 1.49 \\times 1.4 = 2.09$ kW. Wrap angle and $C_\\theta$ are unchanged (same geometry): $C_\\theta \\approx 0.89$. $N_{belts} = \\lceil 2.09/(3.0 \\times 0.89) \\rceil = \\lceil 0.78 \\rceil = 1$ belt.\n\n</details>\n\n<details>\n<summary>Design Task 4 (design decision): one wide belt vs. two narrow belts</summary>\n\nFor the chapter's worked example (2 belts required, B-section), a vendor offers an alternative: a single, wider C-section belt rated at 6.0 kW that alone covers the design power. Which would you choose, and what operational risk does each option carry that the other doesn't?\n\n**Answer:** Either can work; the trade-off is redundancy versus simplicity. Two B-section belts (a \"matched set,\" always replaced together) keep running — at reduced capacity — if one belt is damaged, buying time to schedule a planned changeout rather than an unplanned stoppage; a single C-section belt is simpler to stock and align but a single failure stops the conveyor outright. For a line where unplanned downtime is expensive (this chip conveyor feeding a CNC cell), the two-belt option's partial-failure tolerance is usually worth the extra sheave groove and belt-matching discipline.\n\n</details>\n\n<details>\n<summary>Design Task 5 (plug-in): re-scoring for a fully enclosed, self-lubricating washdown chain</summary>\n\nRe-run the Zone A (primary washdown) weighted matrix from this chapter's worked example, but raise the chain's hygiene score from 1 to 3 (reflecting a self-lubricating, fully guarded washdown chain) and keep every other score and weight the same. Does the recommendation change?\n\n**Answer:** Chain's new Zone A score: $0.15(5)+0.15(5)+0.40(3)+0.20(2)+0.10(4) = 0.75+0.75+1.2+0.4+0.4 = 3.50$. Belt's score is unchanged at 4.35. Belt still wins, but the gap narrows substantially (4.35 vs. 3.50, down from 4.35 vs. 2.70) — a self-lubricating chain closes most of the gap but doesn't fully erase belt's advantage in the highest-hygiene zone.\n\n</details>\n\n<details>\n<summary>Design Task 5 (design decision): auger conveyor gets a chain after all</summary>\n\nDespite Design Task 5's recommendation, the plant's maintenance manager insists on a chain drive for the auger conveyor because of its torque margin and because the plant already stocks that chain pitch for other equipment. What would you require before accepting that decision?\n\n**Answer:** At minimum: a self-lubricating (oil-impregnated bushing) or dry-film-lubricated stainless chain rated for washdown service, not standard carbon-steel chain; a fully enclosed, lubricant-tight guard that also keeps wash water and sanitizer off the chain during cleaning; and a documented relubrication/inspection interval added to the plant's PM schedule. Without all three, the decision trades a hygiene risk for a parts-commonality convenience — acceptable only if it's made explicitly and documented for the next CFIA review, not assumed away.\n\n</details>\n\n<details>\n<summary>Open-Ended Design Scenario: a new secondary conveyor drive</summary>\n\nA food plant is adding a new conveyor in its secondary (packaged-product, non-direct-contact) zone, moving cased product from a case packer to a palletizer. The selected gearmotor delivers 80 N·m continuous torque at 20 rpm on its output shaft, with occasional jam-related torque spikes estimated at up to 1.5x the continuous rating. Using this chapter's methods:\n\n1. Size the connecting shaft (assume 1018 CD steel, $n_d = 3.0$) between the gearmotor and the head pulley.\n2. Determine the diameter increase needed to accommodate a standard keyway ($K_t = 1.6$) at the same design factor.\n3. Select a coupling family, with reasoning, given the jam-related shock potential.\n4. Decide — with reasoning, not just a lookup — whether this drive should use a belt or a chain, given its zone (secondary, not primary washdown) and its torque/speed profile (high torque, low speed).\n\nThere's a specific, defensible answer to each part using only this chapter's tools and the numbers given — work through all four before checking your reasoning against a classmate's.\n\n</details>\n",
    "supporting": [
      "06-09-Shaft-Coupling-Power-Transmission_files\\figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}