{
  "hash": "42f1c4ead1eec160284d305922dd39ca",
  "result": {
    "engine": "knitr",
    "markdown": "---\nengine: knitr\nfilters:\n  - webr\nwebr:\n  show-startup-message: true\n  cell-options:\n    autorun: true\n---\n\n# Bonding, Grounding, and EMC\n\n\n\n## Learning Objectives\n\nBy the end of this chapter, you will be able to:\n\n1. **Distinguish** system grounding, equipment bonding, functional/signal grounding, and shielding, and **explain** why conflating them causes real safety and noise problems.\n2. **Translate** grounding and bonding terminology between the CEC (Section 10) and the NEC (Article 250) when reviewing imported equipment documentation.\n3. **Size** an equipment bonding conductor from the upstream overcurrent device rating, using CEC Table 16 / NEC Table 250.122 practice.\n4. **Apply** the shield-grounded-at-one-end rule for low-frequency signal circuits, and **explain** why VFD cable shielding requires the opposite practice.\n5. **Specify** VFD cabling and motor-frame bonding practice that controls high-frequency common-mode noise and bearing currents.\n6. **Select** an appropriate power/signal separation distance and a star vs. mesh grounding topology for a control panel or cable tray.\n7. **Calculate and compare** touch voltage and fault current for a properly bonded circuit versus one relying solely on a driven ground rod, and **explain** why bonding — not earthing — is what actually clears a fault safely.\n\n## Introduction\n\nA maintenance electrician at a Tier 1 automotive stamping plant near Windsor gets called to a press line where the load-cell signal feeding the PLC's tonnage monitor has started drifting — not failing outright, just noisy enough that the press occasionally flags a false tonnage-limit fault and stops the line. Nothing changed mechanically. What changed is that a new robot cell went in two bays over, complete with a VFD-driven servo-adjacent conveyor, and its installer landed the new equipment's ground wire on the same terminal block as the load-cell's cable shield \"because it was already labeled GND and there was room.\" Two wires, one terminal, one label — and now the plant is bleeding cycle time chasing a problem that traces back to a single word doing four different jobs.\n\nThat word is \"ground,\" and it is genuinely one of the most overloaded terms in industrial electrical work. A raw copper rod driven into the earth outside the building is called a ground. The green wire that lets a motor's frame trip a breaker instantly if it shorts to the winding is called a ground. The 0 V reference inside a PLC power supply is called a ground. The drain wire wrapped around a sensor cable to keep radio-frequency noise off the signal is called a ground. All four are real, all four matter, and none of them do the same job — but because English gives them all the same name, it is easy for someone in a hurry to assume any wire labeled \"ground\" can substitute for any other, with consequences ranging from a nuisance fault on a press line to a genuinely unsafe piece of equipment.\n\nThis chapter builds, from first principles, the vocabulary and the design method to keep these four jobs straight — and then applies that method to seven concrete design tasks that a controls or electrical engineering technologist will actually face on a plant floor: telling the four grounding/bonding/shielding functions apart; translating between how Canada's electrical code and the United States' electrical code name them; sizing an equipment bonding conductor correctly; deciding when a cable shield gets grounded at one end versus both; installing a variable frequency drive (VFD) so it doesn't quietly cook a motor's bearings; laying out a panel so power and signal wiring don't interfere with each other; and — the calculation this chapter is built around — proving, with nothing more than Ohm's law, why a driven ground rod alone will not save someone's life in a fault, but a properly sized bonding conductor will. This chapter connects directly to the [Control Panel Design](06-03-Control-Panel-Design.qmd) chapter, which covers the physical construction of the panels this chapter's bonding and separation rules apply inside, and to the [Motor, Drive, and Gearbox Sizing](06-06-Motor-Drive-Gearbox-Sizing.qmd) chapter, whose VFD-driven motors are exactly the equipment that makes Design Tasks 4 and 5 below necessary in the first place.\n\n## Design Task 1: Four Jobs, One Overloaded Word\n\n### Scenario\n\nBack at the stamping plant, the electrician traces the noisy load-cell signal to that shared terminal block. Before touching anything, she needs to answer a more basic question than \"which wire do I move\": what is each of these two wires actually *for*? Only once that's answered does the fix become obvious — and defensible if anyone asks her to explain it later.\n\n### Design Guidelines and Rules of Thumb\n\nFour distinct electrical functions get called \"ground\" in everyday plant-floor language, and every one of them has a different purpose, a different required impedance, a different current-carrying expectation, and a different governing code rule.\n\n**System grounding** is the connection of the electrical *supply system* itself — typically the secondary neutral of a distribution transformer — to earth through a grounding electrode (a driven rod, a plate, or the building's structural steel or water piping system, per whichever electrode types the code recognizes). Its job is to stabilize the system's voltage relative to earth, give lightning and static a path to dissipate, and limit the voltage stress on insulation during a fault. It is *not* primarily there to clear a fault quickly — as Design Task 7 shows numerically, earth itself is far too resistive a path to do that job on its own.\n\n**Equipment bonding** is the low-impedance conductive connection of all the *normally non-current-carrying metal parts* of an installation — motor frames, panel enclosures, conduit, cable tray, machine frames — together and back to the electrical supply's source. Its job is single-purpose and safety-critical: if a live conductor faults to one of these metal parts, the bonding path must carry enough fault current, with low enough impedance, to make the upstream breaker or fuse trip *fast*. This is the conductor most people mean when they informally say \"ground wire,\" and it is the one this chapter spends the most time on, because getting it wrong is a life-safety issue, not just a nuisance.\n\n**Functional (or signal) grounding** is a voltage *reference* — the 0 V rail a PLC's electronics, an analog input card, or a communication bus measures its signals against. It exists so that a \"5 V\" reading in one device means the same thing as a \"5 V\" reading in another device on the same system. It carries essentially no current in normal operation and is not sized, or intended, to clear a fault. Confusing this with equipment bonding is exactly the stamping-plant electrician's problem: a signal reference conductor is typically small-gauge and shares a path with sensitive analog electronics, which makes it a terrible, noisy, and undersized stand-in for a fault-clearing path — and conversely, an equipment bonding conductor is a terrible signal reference, because it's expected to also carry motor return current, welder ground-return current, or fault current from *other* equipment sharing that same bonding system, all of which shows up as noise on anything using it as a \"clean\" 0 V.\n\n**Shielding** is a conductive layer — foil, braid, or both — wrapped around a signal conductor (or a power cable, for the VFD case in Design Task 4) to intercept electric and magnetic field coupling before it reaches the conductors doing real work. A shield's connection to ground is not there to clear a fault or to hold a reference voltage; it exists purely to give intercepted noise energy somewhere to go, and — as Design Task 4 shows — *how* it's grounded (one end or both, low impedance or not) depends entirely on the frequency of the noise it's fighting.\n\n**Rule of thumb:** if you can't clearly state which single one of these four jobs a given conductor is doing, don't use it for anything until you can. This breaks down only in the sense that it isn't really a rule that \"breaks down\" — it's closer to a discipline check. The one common, defensible exception is that the *equipment bonding* and *system grounding* paths are deliberately tied together at one specific point (the main bonding jumper at the service, discussed further in Design Task 2) — that single, code-defined connection point is intentional and necessary, not a case of the two systems being casually treated as interchangeable everywhere.\n\nCSA C22.1 (the Canadian Electrical Code, Part I, as amended by the Ontario Electrical Safety Code) addresses grounding and bonding in Section 10, and CSA C22.2 No. 0.4 (Bonding of Electrical Equipment) covers the equipment-bonding function specifically. NEC Article 250 (Grounding and Bonding) is the corresponding US reference. IEEE 1100 (the \"Emerald Book,\" Recommended Practice for Powering and Grounding Electronic Equipment) is a widely used industry reference for exactly the functional-grounding-vs-safety-bonding distinction this design task is built around.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Four conductive paths that all get called \"ground\" on a plant floor. Each has a distinct purpose, required impedance, and governing code rule -- treating any two of them as interchangeable is where real problems start.](06-05-Bonding-Grounding-EMC_files/figure-html/fig-06-05-ground-bond-shield-map-1.png){#fig-06-05-ground-bond-shield-map fig-align='center' width=1056}\n:::\n:::\n\n\n### Governing Calculation\n\nThere's no arithmetic formula for telling these four functions apart — this is a classification problem, and classification problems get a decision framework, not an equation. Ask these three questions about any conductor labeled \"ground\":\n\n| Question | If the answer is yes... |\n| :--- | :--- |\n| Does this conductor need to safely carry a large fault current if insulation fails, to make a breaker or fuse trip? | It's an **equipment bonding conductor** — size it per Design Task 3. |\n| Does this conductor connect the electrical supply's neutral point to earth, primarily for voltage stability and surge dissipation? | It's a **system grounding conductor** — sized and routed per the code's grounding electrode rules, not the bonding table. |\n| Does this conductor exist only so two pieces of electronics agree on what \"0 V\" means? | It's a **functional/signal ground** — keep it small, keep it local, and never let it double as a fault path. |\n| Does this conductor's job start and end at intercepting EMI before it reaches a signal pair? | It's a **shield** — its grounding scheme depends on frequency (Design Task 4), not on the rules for the other three. |\n\n### Worked Example\n\nBack to the stamping-plant terminal block. The wire the robot cell's installer landed there is the new robot conveyor's equipment bonding conductor — it needs to carry real fault current back to the panel if the conveyor's motor frame ever becomes energized, and CSA C22.2 No. 0.4 and CEC Section 10 both expect it to be sized and routed as such. The load-cell cable's drain wire is a shield, whose entire job in this low-frequency analog application is to intercept EMI and carry it away, grounded at one end only (Design Task 4 explains why). Landing both on the same terminal block does two things wrong at once: it puts the shield in electrical contact with a conductor that routinely carries motor starting current, VFD switching noise, and — during an actual fault — hundreds of amps, all of which now has a direct, low-impedance path onto the \"quiet\" reference the load cell depends on; and it makes the shield connection point ambiguous, since a shield sharing a terminal with a bonding conductor is, for practical purposes, also grounded at whatever the *other* end of that bonding run happens to be tied to.\n\nThe fix has a definite conclusion: separate the two. The robot conveyor's bonding conductor gets its own dedicated terminal on the bonding bus, per Design Task 3's sizing rule. The load-cell shield gets its own terminal, grounded at one end only, isolated from any conductor that carries load or fault current. This is a five-minute fix once the underlying confusion is resolved — and it's the reason the electrician needed to answer \"what is this wire actually for\" before touching anything.\n\n<details>\n<summary>Industry connection: why this confusion shows up so often on a plant floor</summary>\n\nIn a mixed-trade environment — a plant where power distribution, PLC/instrumentation wiring, and machine safety circuits are sometimes pulled by different crews at different times — \"ground\" gets used as a catch-all label because it's faster to write on a wire tag than \"equipment bonding conductor\" or \"shield drain, single-end termination.\" That labeling shortcut is harmless until two crews, working from the same shorthand, land two functionally different wires on the same terminal. A useful field habit: label every conductor by *function* (BOND, SIG-REF, SHIELD, SYS-GND), not just \"GND\" — it costs nothing and it's exactly the ambiguity that caused the stamping-plant fault.\n\n</details>\n\n## Design Task 2: Terminology Mapping — CEC Section 10 vs. NEC Article 250\n\n### Scenario\n\nAn Ontario systems integrator has just received a packaging machine built by a US OEM. The electrical drawings, the bill of materials, and the machine's UL 508A industrial control panel labeling all use NEC terminology throughout. Before this machine can be accepted, wired into the plant's distribution system, and signed off by the Electrical Safety Authority (ESA) — Ontario's regulator for electrical installations — someone has to read those NEC-labeled drawings and confirm the machine's grounding and bonding scheme actually satisfies CEC Section 10 as adopted by the Ontario Electrical Safety Code. Getting the terminology wrong here isn't just an academic translation exercise; it's the difference between an accurate compliance review and a rubber stamp.\n\n### Design Guidelines and Rules of Thumb\n\nThe CEC and the NEC ultimately require the same underlying protective scheme — a low-impedance fault-current path back to the source, plus a separate connection of the system to earth — but they don't always use the same word for the same conductor, and a technologist trained on one code who reads the other's drawings without knowing this will misread perfectly correct documentation as an error, or worse, wave through an actual gap.\n\nThe single most important distinction: the CEC uses **\"bonding\"** as its general term for the deliberate, low-impedance connection of non-current-carrying metal parts to provide a fault-current path — it's a verb and a noun the CEC applies fairly consistently to this one job. Historically, the NEC used **\"ground\"/\"grounding\"** far more loosely as an umbrella term covering both the fault-current-path function and the earth-connection function, which is exactly the kind of conflation Design Task 1 warns against — the 2020 NEC revised many definitions to sharpen this distinction, but the legacy terminology (starting with \"equipment grounding conductor\" itself) persists because changing established conductor names across an entire installed base of documentation is impractical.\n\n| Concept | CEC (Section 10) term | NEC (Article 250) term | Notes |\n| :--- | :--- | :--- | :--- |\n| Fault-current path from equipment frames back to source | **Bonding conductor** | **Equipment grounding conductor (EGC)** | Same job, different name; sized from Table 16 (CEC) or Table 250.122 (NEC) — see Design Task 3. |\n| Conductor connecting the system (neutral) to the grounding electrode | **Grounding conductor** | **Grounding electrode conductor (GEC)** | Both are the earth-connection conductor, not the fault-clearing path. |\n| Physical earth connection point(s) | **Grounding electrode** | **Grounding electrode** | Terminology converges here — rod, plate, or structural electrode in both codes. |\n| Connection joining the grounded (neutral) conductor to the bonding/grounding system at the service | **Main bonding jumper** | **Main bonding jumper (MBJ)** | One of the few terms where both codes land on the same phrase. |\n| General verb for the fault-path connection function | **\"Bond\" / \"bonded\"** used consistently | **\"Ground\" / \"grounded\"** used historically for both jobs; newer text favors \"bonded\" for this specific function | Read NEC drawings from before ~2020 with extra care — \"grounded\" there may mean *bonded* in CEC terms, not *earthed*. |\n| Enclosure/frame connection of a motor or panel | **Equipment bonding** | **Equipment grounding** | Functionally identical; CEC's phrase is the more precise one for what's actually happening. |\n| Identified circuit conductor (commonly \"neutral\") | **Neutral conductor** (also \"grounded conductor\" in some contexts) | **Grounded conductor** | Largely interchangeable in practice, but don't assume \"grounded conductor\" in an NEC drawing means the bonding/earth system — it means the neutral. |\n\n**Rule of thumb:** whenever a US-drawn machine's documentation says \"ground\" or \"grounded,\" mentally substitute \"bonded\" first and re-read the sentence — in the large majority of industrial equipment contexts (motor frames, enclosures, conduit), that's the function actually being described, and it maps to CEC \"bonding,\" not to a literal earth connection. This breaks down for the small number of genuine earth-connection references (grounding electrode, grounding electrode conductor, driven rod resistance testing) — there, \"ground\" really does mean earth, and substituting \"bonded\" would be wrong. When in doubt, check whether the conductor in question terminates at an electrode driven into the earth (system grounding) or at the equipment's own frame/enclosure (bonding) — that single check resolves the ambiguity every time.\n\nCEC Section 10 (as adopted and amended by the Ontario Electrical Safety Code) and CSA C22.2 No. 0.4 govern this on the Canadian side; NEC Article 250 is the US equivalent. Also worth noting, since it comes up constantly on the same imported-equipment drawings: Canadian practice commonly specifies motors and distribution up to a 600 V class, where US practice more commonly centers on 480 V — a voltage-class difference, not a terminology difference, but one that shows up on the same drawing sets and is worth checking alongside the grounding/bonding terms.\n\n### Governing Calculation\n\nTranslating a US-drawn document into CEC terms is a procedure, not a formula:\n\n1. **Identify the function** the NEC-labeled conductor is actually performing, using Design Task 1's three-question framework — not just its NEC name.\n2. **Look up the CEC equivalent term** from the mapping table above.\n3. **Re-verify the numeric requirement independently** — never assume an NEC Table 250.122 conductor size satisfies CEC Table 16, or vice versa. The two tables are built on similar logic (bonding conductor size keyed to upstream OCPD rating) but are not guaranteed to produce identical AWG selections at every breakpoint, and only the code actually in force for the installation governs.\n4. **Document the mapping** in the compliance review — for an ESA submission or a field evaluation, showing the reviewer's term-by-term translation is often what turns a slow, back-and-forth review into a fast one.\n\n### Worked Example\n\nThe packaging machine's drawings specify a \"10 AWG equipment grounding conductor\" bonding the main control panel to the machine frame, sized per a note referencing \"NEC Table 250.122\" for the machine's 60 A branch circuit protective device. Following the procedure: step 1 identifies this as a fault-current path (it bonds a frame, sized off an OCPD rating, not a voltage reference) — so per Design Task 1's framework, this is functionally CEC's **bonding conductor**, not a grounding-electrode connection. Step 2 confirms the CEC term to use in the compliance report is \"bonding conductor,\" sized per **CEC Table 16**, not \"grounding conductor.\" Step 3 is the step that actually matters for sign-off: the integrator pulls CEC Table 16 independently and checks the minimum bonding conductor size for a 60 A branch circuit OCPD under CEC rules, rather than assuming the NEC-derived 10 AWG figure on the drawing is automatically correct for a CEC installation (in this case, per Design Task 3's illustrative table, 10 AWG is in fact consistent with a 60 A OCPD — but that has to be checked, not assumed). Step 4 produces a one-line note for the ESA submission package: \"Machine's NEC-labeled 10 AWG EGC verified equivalent to and compliant with CEC Table 16 bonding conductor requirement for the installed 60 A branch OCPD.\" That's a documented, defensible translation — not a guess.\n\n<details>\n<summary>Industry connection: why this matters for imported automation equipment</summary>\n\nAutomotive and food-processing plants in Ontario routinely install robot cells, packaging machinery, and processing equipment built by US or offshore OEMs, wired and labeled to NEC/UL conventions from the factory. The equipment itself doesn't need to be rebuilt to CEC terminology — but whoever signs off on the installation for ESA acceptance does need to be able to read the NEC-labeled drawings correctly and verify, term by term, that the actual protective scheme satisfies CEC Section 10. Getting this translation wrong in either direction — assuming NEC numbers are automatically CEC-compliant, or assuming unfamiliar NEC terms mean something is missing when it isn't — both cost real time in commissioning.\n\n</details>\n\n## Design Task 3: Sizing the Equipment Bonding Conductor\n\n### Scenario\n\nA food processing plant is adding a washdown-rated VFD-driven conveyor to move sealed product cartons from a filling line to a case packer. The conveyor's 11 kW motor is protected by a 60 A fused disconnect. Downstream, the same plant's electrical room feeds an entire motor control centre (MCC) lineup — several conveyor and pump motors together — through a single 400 A feeder breaker. The electrician on the job needs to size the equipment bonding conductor for both circuits, and the branch-circuit motor's relatively small full-load current is tempting him to reason \"small motor, small bonding wire.\" That reasoning is wrong, and understanding *why* it's wrong is this design task's entire point.\n\n### Design Guidelines and Rules of Thumb\n\nAn equipment bonding conductor is not sized like an ordinary current-carrying conductor. A branch-circuit or feeder conductor's ampacity is selected to carry the *load's continuous current* without overheating — bigger load, bigger wire, in a roughly proportional relationship. An equipment bonding conductor's job is completely different: it only ever carries meaningful current for a brief moment, during a fault, and its size is chosen so that during that brief moment it can safely carry enough fault current, at low enough impedance, to make the *upstream overcurrent device* — not the motor, not the connected load — trip fast. That's why bonding conductor size is selected directly from the rating of the breaker or fuse protecting the circuit, using a lookup table, not calculated from the motor's full-load amps (FLA).\n\n$$A_{bond} = \\text{Table}(I_{OCPD})$$\n\nThis relationship is a monotonically non-decreasing step function of the upstream OCPD rating — CEC Table 16 on the Canadian side, NEC Table 250.122 as the US equivalent — and it is deliberately *not* proportional to the actual connected load. A washdown conveyor motor drawing 15 A on a 60 A-protected branch and a much larger motor drawing 55 A on the same 60 A-protected branch both need the *identical* bonding conductor size, because both circuits are protected by, and depend on, the same 60 A device tripping under fault conditions. The table below is an **illustrative, representative summary** of the general shape of this relationship — always pull the actual CEC Table 16 or NEC Table 250.122 value for a real installation; these are not the published table values.\n\n\n::: {#tbl-06-05-bonding-illustrative .cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover table-condensed\" style=\"margin-left: auto; margin-right: auto;\">\n<caption>Illustrative bonding conductor sizing (representative shape only -- consult CEC Table 16 or NEC Table 250.122 for actual values)</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:right;font-weight: bold;color: white !important;background-color: rgba(74, 134, 199, 1) !important;\"> OCPD Rating, Not Exceeding (A) </th>\n   <th style=\"text-align:left;font-weight: bold;color: white !important;background-color: rgba(74, 134, 199, 1) !important;\"> Min. Copper Bonding Conductor (illustrative) </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:right;\"> 20 </td>\n   <td style=\"text-align:left;\"> 12 AWG </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 30 </td>\n   <td style=\"text-align:left;\"> 10 AWG </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 60 </td>\n   <td style=\"text-align:left;\"> 10 AWG </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 100 </td>\n   <td style=\"text-align:left;\"> 8 AWG </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 200 </td>\n   <td style=\"text-align:left;\"> 6 AWG </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 400 </td>\n   <td style=\"text-align:left;\"> 3 AWG </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 600 </td>\n   <td style=\"text-align:left;\"> 1 AWG </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 800 </td>\n   <td style=\"text-align:left;\"> 1/0 AWG </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 1 000 </td>\n   <td style=\"text-align:left;\"> 2/0 AWG </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 1 200 </td>\n   <td style=\"text-align:left;\"> 3/0 AWG </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n**Rule of thumb:** always round up to the next standard conductor size listed in the table — never interpolate down to save copper — and re-check the bonding conductor size any time the upstream OCPD rating changes, even if the connected load and the branch conductor's own ampacity haven't changed at all. This breaks down at the extreme high end of both tables: beyond their largest listed OCPD breakpoint, CEC Table 16 and NEC Table 250.122 both shift to a different rule entirely — sizing the bonding conductor as a percentage of the circular mil (or mm²) area of the largest ungrounded phase conductor in the same circuit, rather than continuing the simple OCPD lookup. That transition point is exactly the kind of detail worth re-verifying against the actual table for a large-feeder job, not assuming from a smaller-circuit rule of thumb.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Bonding conductor size tracks the upstream OCPD rating in discrete steps -- not a smooth, proportional function of either the OCPD rating or the actual connected load current.](06-05-Bonding-Grounding-EMC_files/figure-html/fig-06-05-bonding-size-steps-1.png){#fig-06-05-bonding-size-steps fig-align='center' width=960}\n:::\n:::\n\n\n### Worked Example\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Illustrative bonding conductor lookup table (representative shape only --\n## consult CEC Table 16 / NEC Table 250.122 for the actual published values)\nocpd_breakpoints <- c(20, 30, 60, 100, 200, 400, 600, 800, 1000, 1200)\nbond_awg         <- c(\"12 AWG\", \"10 AWG\", \"10 AWG\", \"8 AWG\", \"6 AWG\",\n                       \"3 AWG\", \"1 AWG\", \"1/0 AWG\", \"2/0 AWG\", \"3/0 AWG\")\n\nlookup_bonding_size <- function(ocpd_rating) {\n  idx <- min(which(ocpd_breakpoints >= ocpd_rating))\n  bond_awg[idx]\n}\n\n## Case 1: washdown conveyor motor branch circuit, food processing plant\nocpd_branch <- 60          # A, fused disconnect protecting the branch\nmotor_FLA   <- 15.4        # A, nameplate FLA of the 11 kW washdown motor\n\n## Case 2: MCC feeder serving several such motors, same plant\nocpd_feeder    <- 400      # A, feeder OCPD rating\nconnected_load <- 180      # A, sum of connected motor FLAs on the feeder\n\nbond_branch <- lookup_bonding_size(ocpd_branch)\nbond_feeder <- lookup_bonding_size(ocpd_feeder)\n\ncat(\"Case 1 -- Branch circuit:\\n\")\ncat(sprintf(\"  OCPD rating: %d A -> required bonding conductor: %s\\n\", ocpd_branch, bond_branch))\ncat(sprintf(\"  Motor FLA: %.1f A (only %.0f%% of the OCPD rating)\\n\\n\",\n            motor_FLA, motor_FLA / ocpd_branch * 100))\n\ncat(\"Case 2 -- MCC feeder:\\n\")\ncat(sprintf(\"  OCPD rating: %d A -> required bonding conductor: %s\\n\", ocpd_feeder, bond_feeder))\ncat(sprintf(\"  Connected load: %d A (%.0f%% of the OCPD rating)\\n\\n\",\n            connected_load, connected_load / ocpd_feeder * 100))\n\ncat(sprintf(\"OCPD rating increased %.1fx (from %d A to %d A)\\n\",\n            ocpd_feeder / ocpd_branch, ocpd_branch, ocpd_feeder))\ncat(\"Bonding conductor size followed the OCPD step table, not a direct\\n\")\ncat(\"proportional scaling of either the OCPD ratio or the load-current ratio.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCase 1 -- Branch circuit:\n  OCPD rating: 60 A -> required bonding conductor: 10 AWG\n  Motor FLA: 15.4 A (only 26% of the OCPD rating)\n\nCase 2 -- MCC feeder:\n  OCPD rating: 400 A -> required bonding conductor: 3 AWG\n  Connected load: 180 A (45% of the OCPD rating)\n\nOCPD rating increased 6.7x (from 60 A to 400 A)\nBonding conductor size followed the OCPD step table, not a direct\nproportional scaling of either the OCPD ratio or the load-current ratio.\n```\n\n\n:::\n:::\n\n\n**Sanity check:** the branch circuit's motor uses only 26% of its 60 A OCPD's rating, and the feeder's connected load uses only 45% of its 400 A OCPD's rating — in both cases the bonding conductor was sized entirely off the OCPD, with the actual load current playing no role in the lookup at all. That's the concept this design task exists to teach: an electrician who tried to \"right-size\" the bonding conductor to the 15.4 A motor FLA instead of the 60 A OCPD rating would undersize it dramatically, leaving too little fault-current capacity for the very event — a short circuit — the conductor exists to handle.\n\n<details>\n<summary>Industry connection: washdown bonding hardware in food processing</summary>\n\nBonding conductors and their termination hardware in a food plant's washdown zones see a harsher environment than a typical dry industrial panel: daily high-pressure caustic or acid cleaning chemicals, frequent equipment removal for sanitation access, and IP69K-rated enclosures that get opened and re-closed often. Stainless steel or corrosion-resistant-plated bonding lugs and jumpers, rated for the washdown environment, matter here as much as the conductor size itself — a correctly sized bonding conductor terminated on a corroding lug is no longer a low-impedance path, and corrosion at a bonding connection is exactly the kind of failure that's invisible until the fault it was supposed to clear happens.\n\n</details>\n\n## Design Task 4: Ground Loops, the One-End Shield Rule, and the VFD Exception\n\n### Scenario\n\nA beverage plant runs an 85 m instrument cable from a tank-level 4-20 mA transmitter back to a PLC analog input, routed through a common cable tray alongside power feeders. Two problems show up on two different machines at the same plant, and they have opposite correct answers — which is exactly why this design task exists. First, the level signal develops intermittent noise whenever a large compressor motor starts nearby. Second, a completely different VFD-fed conveyor drive, 15 m from its motor, has been generating radiated EMI that's tripping a nearby wireless access point — and the electrician's first instinct, \"ground the shield better,\" is about to make one of these two problems worse if he applies the same fix to both.\n\n### Design Guidelines and Rules of Thumb\n\nAt signal and power frequencies — DC up to roughly the audio range, which covers 4-20 mA loops, thermocouples, RTDs, and most encoder feedback — a cable shield should be grounded at **one end only**. The reason is a ground loop: if the shield is bonded to ground at both ends, and the grounding system's local potential isn't perfectly uniform everywhere (it never is — nearby motor starts, welders, or even normal load current flowing through the plant's bonding/grounding network all create small, real potential differences between two physically separated ground points), the shield becomes a closed conductive loop between those two slightly different potentials. Current flows in that loop, driven by the potential difference and limited only by the shield's own resistance — and that circulating current couples noise into the signal conductors it's supposed to be protecting. Grounding the shield at one end only breaks the loop: with no closed path, no current can circulate, no matter how large the potential difference between the two ends becomes.\n\nAt VFD and drive frequencies, the physics that makes the one-end rule correct stops applying, and the correct practice **inverts**. A VFD's output is not a clean sine wave — it's a fast-switched PWM waveform, and the switching edges themselves (not just the fundamental output frequency) contain significant high-frequency common-mode energy, often extending from the hundreds of kHz into the low MHz range. That high-frequency common-mode current needs a very low-impedance path back to its source (the drive) at *both* ends of the cable — and a single-point connection, especially a \"pigtail\" (a short lead of wire connecting the shield to a ground lug), has far too much *inductive* impedance at these frequencies to do that job, even though the exact same pigtail is functionally perfect at 60 Hz. The correct VFD cable practice is therefore a low-impedance **360° bond** — a proper cable gland or EMC backshell making contact around the shield's entire circumference — at **both** the drive end and the motor end.\n\n**Rule of thumb:** ground low-level analog and instrumentation cable shields at one end only; ground VFD (and other high-frequency drive) cable shields with a 360° low-impedance termination at both ends. This breaks down at the boundary between the two regimes — a cable carrying both low-level analog signals and running near high-frequency switching noise sometimes needs a hybrid approach (a shield grounded at one end for the fundamental signal, with a separate high-frequency bypass capacitor at the far end to shunt only the high-frequency noise to ground without closing a low-frequency loop) — a detail worth escalating to an EMC specialist rather than guessing on a mixed-frequency cable.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Low-frequency instrumentation shielding: grounding the shield at both ends closes a loop that a small ground-potential difference can drive current through; grounding at one end only leaves the loop open.](06-05-Bonding-Grounding-EMC_files/figure-html/fig-06-05-shield-ground-loop-1.png){#fig-06-05-shield-ground-loop fig-align='center' width=1056}\n:::\n:::\n\n\n### Worked Example\n\nLive cell — try a different cable length, shield resistance, or ground potential difference and see how the circulating current responds.\n\n```{webr-r}\n#| label: ground-loop-current-06-05\n## Ground loop scenario: 4-20 mA level transmitter loop, beverage plant,\n## cable run parallel to power feeders in a common tray\ncable_length_m <- 85      # m, transmitter to PLC analog input\nshield_R_per_m <- 0.030   # ohm/m, drain wire + foil shield, representative\nshield_R_total <- cable_length_m * shield_R_per_m\n\n## Ground potential difference between the two ends of the run, induced by\n## a large compressor motor starting nearby (a realistic, if intermittent, event)\ndelta_V_ground <- 1.2     # V, transient potential difference during motor start\n\n## Case A: shield grounded at BOTH ends (a mis-wired installation) --\n## forms a closed loop, so current actually circulates on the shield\nI_loop_both_ends <- delta_V_ground / shield_R_total\n\n## Case B: shield grounded at ONE end only (correct low-frequency practice) --\n## no closed path exists, so no circulating current is possible\nI_loop_one_end <- 0\n\ncat(sprintf(\"Shield resistance over %.0f m: %.2f ohm\\n\", cable_length_m, shield_R_total))\ncat(sprintf(\"Transient ground potential difference: %.1f V\\n\\n\", delta_V_ground))\ncat(sprintf(\"Shield grounded at BOTH ends: I_loop = %.1f V / %.2f ohm = %.0f mA circulating\\n\",\n            delta_V_ground, shield_R_total, I_loop_both_ends * 1000))\ncat(sprintf(\"Shield grounded at ONE end only: I_loop = %.0f mA (no closed path exists)\\n\",\n            I_loop_one_end * 1000))\ncat(sprintf(\"\\nThat %.0f mA doesn't touch the signal conductors directly, but it flows\\n\", I_loop_both_ends * 1000))\ncat(\"the full length of the shield and couples into the twisted pair through\\n\")\ncat(\"imperfect shield-to-conductor coupling -- exactly the noise mechanism\\n\")\ncat(\"the single-end rule exists to prevent.\\n\")\n```\n\n**Sanity check:** a 1.2 V transient during a nearby motor start sounds tiny next to a 347 V or 600 V distribution system, and it is — but the 4-20 mA signal it's corrupting only spans 16 mA end to end, so even a modest circulating current, imperfectly coupled onto the signal pair, is large relative to the signal itself. Grounding the shield at one end doesn't reduce that 1.2 V potential difference — it makes the potential difference irrelevant, because there's no longer a closed path for it to drive current through.\n\nNow the VFD cable, where the opposite fix applies. Live cell — try a different pigtail length or edge rise time and see how the reactance comparison changes.\n\n```{webr-r}\n#| label: pigtail-reactance-06-05\n## VFD shielded cable termination: pigtail vs. 360-degree low-impedance clamp\n## Rule of thumb: an unshielded straight lead has ~1 nH of self-inductance per mm\nL_pigtail_mm <- 120                  # mm, typical drain-wire pigtail length\nL_pigtail_H  <- L_pigtail_mm * 1e-9  # ~1 nH/mm rule of thumb -> H\n\nL_clamp_H <- 2e-9   # H, residual inductance of a proper 360-degree gland/backshell\n\n## Representative frequencies: 60 Hz power/instrumentation frequency, and a\n## VFD switching-edge \"knee frequency\" (rule of thumb: f_knee = 0.35 / t_rise)\nf_60hz   <- 60\nt_rise_s <- 50e-9         # s, representative IGBT output edge rise time\nf_knee   <- 0.35 / t_rise_s\n\nX_pigtail_60hz <- 2 * pi * f_60hz * L_pigtail_H\nX_clamp_60hz   <- 2 * pi * f_60hz * L_clamp_H\nX_pigtail_knee <- 2 * pi * f_knee * L_pigtail_H\nX_clamp_knee   <- 2 * pi * f_knee * L_clamp_H\n\ncat(sprintf(\"Pigtail lead inductance (%.0f mm @ ~1 nH/mm): %.0f nH\\n\", L_pigtail_mm, L_pigtail_H * 1e9))\ncat(sprintf(\"360-degree clamp residual inductance: %.1f nH\\n\\n\", L_clamp_H * 1e9))\ncat(sprintf(\"VFD switching edge rise time: %.0f ns -> knee frequency ~ %.1f MHz\\n\\n\",\n            t_rise_s * 1e9, f_knee / 1e6))\n\ncat(\"At 60 Hz (power/instrumentation frequency):\\n\")\ncat(sprintf(\"  Pigtail reactance: %.6f ohm\\n\", X_pigtail_60hz))\ncat(sprintf(\"  360-degree clamp reactance: %.6f ohm\\n\", X_clamp_60hz))\ncat(\"  -> both utterly negligible; either termination style works fine\\n\\n\")\n\ncat(sprintf(\"At the %.1f MHz switching-edge knee frequency:\\n\", f_knee / 1e6))\ncat(sprintf(\"  Pigtail reactance: %.2f ohm\\n\", X_pigtail_knee))\ncat(sprintf(\"  360-degree clamp reactance: %.3f ohm\\n\", X_clamp_knee))\ncat(\"  -> pigtail is now a real obstruction to the high-frequency common-mode\\n\")\ncat(\"     current; the clamp stays comfortably low\\n\")\n```\n\n**Sanity check:** the pigtail's inductance never changes — it's the same 120 nH lead at both frequencies. What changes is the frequency multiplying it. At 60 Hz, that inductance is such a small contributor to impedance that it's irrelevant, which is exactly why the one-end low-frequency rule can be satisfied with an ordinary drain wire. At the VFD's MHz-range switching content, the identical pigtail's reactance climbs into several ohms — no longer negligible next to the sub-ohm impedance a high-frequency bond actually needs to achieve — which is why VFD cable needs the 360° clamp, not a pigtail, and needs it at both ends.\n\n<details>\n<summary>Industry connection: getting this backwards on the plant floor</summary>\n\nIt's common to see a well-meaning electrician \"improve\" a noisy VFD installation by adding a second ground wire pigtail at the motor end, reasoning that more grounding connections must be better — without realizing that a second *pigtail* (rather than a proper 360° termination) still leaves several ohms of high-frequency impedance in the path, so it does little to fix the actual EMI problem. Conversely, it's just as common to see a 4-20 mA loop's shield grounded at both ends \"to be extra safe\" against a fault — which, as the worked example above shows, is precisely the wrong instinct at that frequency. The fix in both cases is the same: match the termination style to the frequency actually present on that cable, not to a generic instinct about what \"more grounding\" does.\n\n</details>\n\n## Design Task 5: VFD Cabling, Motor Frame Bonding, and Bearing Currents\n\n### Scenario\n\nAn automotive body-in-white plant runs a dozen VFD-driven conveyors and several robot-mounted servo axes off a shared 600 V distribution bus, all switching at similar carrier frequencies within the same building. Six months after startup, the maintenance team starts finding a pattern on vibration analysis: several of the induction motors on the VFD-fed conveyors are showing early bearing wear with a distinctive fluted pattern on the races — not a lubrication or load problem, but something electrical. The plant's reliability engineer needs to explain the mechanism to the maintenance team and specify what changes in cabling and bonding practice, going forward, to stop it.\n\n### Design Guidelines and Rules of Thumb\n\nA VFD's output isn't a clean three-phase sine wave referenced to a stable neutral — it's built from fast PWM switching against a DC bus, and because the three output phases don't sum to zero at every instant of the switching pattern the way a true sine wave would, the drive produces a **common-mode voltage**: a voltage between the motor's electrical system as a whole and ground, switching at the drive's carrier frequency. That common-mode voltage capacitively couples across the motor's internal air gaps — stator winding to frame, stator to rotor — and a fraction of it appears across the thin lubricating film inside the motor's own bearings. When that voltage exceeds the film's dielectric strength, it breaks down and discharges through the bearing itself, like a tiny, repeated electrical discharge machining (EDM) event, every switching cycle, for the life of the drive. Over months, thousands of these micro-discharges pit the races into the fluted wear pattern the reliability engineer is looking at.\n\nThe governing relationship is a simplified capacitive voltage-divider model: the motor's own internal geometry (winding-to-frame and winding-to-rotor capacitances) sets a **bearing voltage ratio (BVR)** — the fraction of the drive's common-mode voltage that actually appears across the bearing film.\n\n$$V_{bearing} = BVR \\times V_{cm}$$\n\n| Symbol | Description | Unit |\n| :--- | :--- | :--- |\n| $V_{cm}$ | Peak common-mode voltage produced by the drive's switching | V |\n| $BVR$ | Bearing voltage ratio — fraction of $V_{cm}$ capacitively coupled across the bearing film (unmitigated, typically 3-6% for a standard induction motor) | dimensionless |\n| $V_{bearing}$ | Estimated peak voltage across the bearing oil/grease film | V |\n\n**Rule of thumb:** treat 3-6% as a representative unmitigated BVR for a standard-frame induction motor with no bearing-current mitigation, and treat this whole model as an order-of-magnitude planning tool, not a substitute for a manufacturer's actual bearing-current guidance (NEMA MG 1 Part 31 and IEC 60034-25 both address inverter-fed motor bearing currents specifically). This breaks down for motors already built with mitigation in mind — motors with an insulated non-drive-end bearing, an integrated shaft grounding device, or a hybrid-ceramic bearing package have a fundamentally different (and much lower) effective discharge path, and the simple BVR model doesn't capture that design difference.\n\nOnce a common-mode voltage is present, controlling where its current actually flows is a cabling and bonding problem as much as a motor problem. **Symmetrical, shielded VFD cable** — three phase conductors plus a ground/bonding conductor arranged with true geometric symmetry inside an overall low-impedance shield — keeps the common-mode current balanced and gives it a deliberate, low-impedance return path along the cable shield itself, terminated with the 360° bond from Design Task 4 at both the drive and motor ends. Without that low-impedance shield path, the common-mode current still has to return to the drive somehow — and it will find whatever path has the lowest impedance available, which is often straight through the motor frame, through the bearings, through the driven machine's frame, and back through whatever bonding or structural steel path happens to be available. That's the mechanism connecting poor VFD cabling practice directly to bearing fluting: a low-impedance shield path gives the noise somewhere harmless to go; without one, the bearings themselves become part of the return circuit.\n\nA secondary, common-mode-independent mitigation is a dedicated **shaft grounding ring or brush**, which provides a very low-impedance path from the rotating shaft directly to the motor frame — bypassing the bearing entirely, so discharge current takes that path instead of arcing through the bearing film. An **insulated bearing** at the non-drive end (a ceramic-coated or ceramic-ball bearing) works by the opposite mechanism: instead of giving current an easy path, it blocks the circulating bearing-current loop from closing through that bearing at all. A **common-mode choke** on the drive's output reduces $V_{cm}$ itself at the source, lowering the common-mode voltage available to couple into the bearing in the first place — which the worked example below quantifies directly.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Common-mode current from a VFD's switching has to return to the drive somehow. A low-impedance shield path (top) gives it a harmless route; without one, it finds its way through the motor's bearings (bottom).](06-05-Bonding-Grounding-EMC_files/figure-html/fig-06-05-bearing-current-path-1.png){#fig-06-05-bearing-current-path fig-align='center' width=1056}\n:::\n:::\n\n\n### Worked Example\n\nLive cell — try a different line voltage, BVR, or choke reduction percentage and see how the bearing voltage estimate responds.\n\n```{webr-r}\n#| label: bearing-voltage-06-05\n## VFD common-mode voltage and bearing voltage estimate\nV_line_rms <- 600                  # V, three-phase line-to-line (CEC 600 V motor class)\nV_dc_bus   <- 1.35 * V_line_rms    # V, typical diode-bridge DC bus voltage\n\n## Representative peak common-mode voltage: roughly half the DC bus\nV_cm_peak <- V_dc_bus / 2\n\n## Bearing voltage ratio (BVR) rule of thumb for an unmitigated induction\n## motor: typically 3-6% of the common-mode voltage appears across the\n## bearing oil film via capacitive coupling\nBVR <- 0.04\nV_bearing <- BVR * V_cm_peak\n\n## Representative order-of-magnitude dielectric breakdown voltage of a\n## thin bearing grease/oil film\nV_film_breakdown <- 10   # V\n\ncat(sprintf(\"DC bus voltage: %.0f V\\n\", V_dc_bus))\ncat(sprintf(\"Representative peak common-mode voltage: %.0f V\\n\", V_cm_peak))\ncat(sprintf(\"Bearing voltage ratio (unmitigated): %.0f%%\\n\", BVR * 100))\ncat(sprintf(\"Estimated bearing voltage: %.1f V\\n\\n\", V_bearing))\ncat(sprintf(\"Representative film breakdown voltage: ~%.0f V\\n\", V_film_breakdown))\ncat(sprintf(\"-> %s: estimated bearing voltage %s the film's breakdown threshold\\n\\n\",\n            ifelse(V_bearing > V_film_breakdown, \"AT RISK\", \"LIKELY OK\"),\n            ifelse(V_bearing > V_film_breakdown, \"exceeds\", \"stays below\")))\n\n## Mitigation: common-mode choke on the drive output\nchoke_reduction_pct <- 50\nV_cm_mitigated       <- V_cm_peak * (1 - choke_reduction_pct / 100)\nV_bearing_mitigated  <- BVR * V_cm_mitigated\n\ncat(sprintf(\"With a common-mode choke reducing peak CM voltage by %.0f%%:\\n\", choke_reduction_pct))\ncat(sprintf(\"  Mitigated peak CM voltage: %.0f V\\n\", V_cm_mitigated))\ncat(sprintf(\"  Mitigated bearing voltage: %.1f V -> %s\\n\", V_bearing_mitigated,\n            ifelse(V_bearing_mitigated > V_film_breakdown, \"still AT RISK\", \"now LIKELY OK\")))\n```\n\n**Sanity check:** an unmitigated bearing voltage of roughly 16 V comfortably exceeds a representative few-volt-to-low-tens-of-volts film breakdown threshold, which is consistent with the fluting damage the reliability engineer is actually seeing in the field — the model reproduces the observed failure mode, which is a reasonable order-of-magnitude confidence check. Cutting the common-mode voltage in half (a realistic result of a properly selected common-mode choke) drops the estimated bearing voltage below the breakdown threshold — but note this is only one of several viable mitigations, and a plant with a dozen already-installed VFDs showing this problem will often find it faster and cheaper to retrofit shaft grounding rings on the affected motors than to replace cabling or add chokes to every drive.\n\n<details>\n<summary>Industry connection: why one bad cable run affects an entire automotive line</summary>\n\nWith a dozen VFD-driven conveyors and robots sharing the same 600 V distribution bus and, often, common structural steel and cable tray runs, a single conveyor installed without proper symmetrical shielded cable and 360° bonding doesn't just risk that one motor's bearings — its common-mode noise can ride the shared bonding and structural-steel network and show up as elevated bearing voltage on *other* nearby VFD-fed equipment that was, on its own, correctly installed. This is exactly why plant standards for automotive lines with many drives typically specify uniform cabling and bonding practice across every VFD, not just the ones that have already shown a problem.\n\n</details>\n\n## Design Task 6: Panel Layout — Separation Distance and Star vs. Mesh Grounding\n\n### Scenario\n\nA controls integrator is laying out a new panel for an automotive body-shop line with 14 interconnected sub-panels sharing a common cable tray system, several VFD-driven robots and conveyors, and a mix of high-speed digital fieldbus and analog instrumentation wiring. A separate, much smaller job at a food processing plant needs a single washdown-rated control panel for one conveyor skid, with three analog instruments (a level probe, a pressure transmitter, and a temperature RTD) and no VFD at all. Both jobs need a grounding topology decision and a wiring separation plan — but, as this design task shows, the right answer for one is not automatically the right answer for the other.\n\n### Design Guidelines and Rules of Thumb\n\nRouting power and signal wiring too close together for too long a parallel run lets the power wiring's changing current induce noise into the signal wiring, even with no direct electrical connection between them — a purely magnetic (and, to a lesser extent, capacitive) coupling effect that gets worse with longer parallel runs, higher power currents, and closer spacing. The practical fix is separation distance, and the amount of separation needed depends on how sensitive the signal wiring is and how \"noisy\" the power wiring is.\n\n| Wiring class | Typical content | Illustrative min. separation from power circuits >20 A |\n| :--- | :--- | :--- |\n| Sensitive analog (Level 1) | 4-20 mA loops, thermocouples, RTDs, low-level encoder feedback | 300 mm (12 in) |\n| Digital / communication (Level 2) | Fieldbus, Ethernet, discrete digital I/O | 150 mm (6 in) |\n| Power / motor leads (Level 3-4) | VFD output, motor feeders, welding circuits | reference class — not itself derated |\n\n**Rule of thumb:** keep at least 150-300 mm (6-12 in) of separation between power wiring and signal wiring for parallel runs in the same tray or panel, using the larger figure for the most sensitive analog circuits and VFD output cable specifically, and cross at 90° wherever a crossing is unavoidable — a perpendicular crossing needs essentially no extra separation, since the coupling effect is dominated by parallel run length, not by a brief crossing point. This breaks down for very short parallel runs (a few hundred mm) even at close spacing, where the coupled noise energy is often too small to matter regardless of the listed separation — and it also breaks down in the other direction for very high-current or very long parallel runs (a welding feeder, a large VFD output cable run over tens of metres), where even the \"sensitive analog\" separation figure may not be enough and a dedicated, separately routed conduit is worth the extra cost. IEEE 518 (Guide for the Installation of Electrical Equipment to Minimize Electrical Noise Inputs to Controllers from External Sources) is the standard reference for this kind of wiring-class separation guidance.\n\nThe second layout decision is grounding **topology**: how the bonding/reference connections of multiple enclosures relate to each other. A **star (single-point) topology** ties every enclosure's reference back to one common point, with no other conductive path between enclosures — this avoids ground loops between enclosures entirely, which is exactly what a small panel full of sensitive, low-frequency analog instrumentation wants. A **mesh (multi-point grid) topology** bonds every enclosure to its neighbours and to a common grid at multiple points, deliberately creating many parallel low-impedance paths — which is exactly what a large, high-frequency-noise-heavy installation wants, because at high frequencies a single-point star topology's connecting conductors become significant inductive impedances (the same pigtail-inductance effect from Design Task 4), and only a low-impedance grid keeps the whole system at a consistent reference across a wide frequency range.\n\n**Rule of thumb:** default to a star topology for a single panel or a small group of panels dominated by low-frequency analog instrumentation with no VFDs present; default to a mesh/grid topology for a large, multi-panel installation with VFDs, servo drives, or other high-frequency switching noise sources. This breaks down for large installations that also carry sensitive analog instrumentation — the common real-world answer there is a **hybrid**: a mesh/grid bonding system tying all the enclosures together for high-frequency performance, with a star topology built *within* each individual panel for its own sensitive analog wiring, isolated from the panel-to-panel grid except at one deliberate point. IEEE 1100 (the \"Emerald Book\") is the standard reference most often cited for this star-vs-mesh topology guidance.\n\n\n::: {#tbl-06-05-separation-distance .cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover table-condensed\" style=\"margin-left: auto; margin-right: auto;\">\n<caption>Illustrative power/signal separation guidance (representative practitioner ranges -- see IEEE 518 for an actual project)</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;font-weight: bold;color: white !important;background-color: rgba(74, 134, 199, 1) !important;\"> Layout Situation </th>\n   <th style=\"text-align:left;font-weight: bold;color: white !important;background-color: rgba(74, 134, 199, 1) !important;\"> Illustrative Guidance </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> Parallel run, sensitive analog vs. power &gt;20 A </td>\n   <td style=\"text-align:left;\"> 300 mm (12 in) minimum </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Parallel run, digital/fieldbus vs. power &gt;20 A </td>\n   <td style=\"text-align:left;\"> 150 mm (6 in) minimum </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Any wiring class, crossing power at 90 degrees </td>\n   <td style=\"text-align:left;\"> no significant separation required </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> VFD output cable vs. any signal wiring, long parallel run </td>\n   <td style=\"text-align:left;\"> 300 mm (12 in) minimum, or separate conduit </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Star (single-point) grounding topology avoids ground loops between panels, ideal for a small analog-heavy installation. Mesh (multi-point grid) topology keeps impedance low across a wide frequency range, needed once VFDs and multiple interconnected panels are involved.](06-05-Bonding-Grounding-EMC_files/figure-html/fig-06-05-star-mesh-topology-1.png){#fig-06-05-star-mesh-topology fig-align='center' width=1056}\n:::\n:::\n\n\n### Worked Example\n\nLive cell — try different weights or scores (what matters most for *your* installation?) and see whether the recommendation flips.\n\n```{webr-r}\n#| label: star-mesh-decision-06-05\n## Star vs. mesh grounding topology -- weighted decision matrix\n## Scenario: automotive body-shop line, 14 interconnected panels sharing a\n## common tray, several VFD-driven robots and conveyors\nweights <- c(panel_count = 0.25, hf_noise_content = 0.30,\n             sensitive_analog = 0.20, maintenance_ease = 0.25)\n\nstar_scores <- c(panel_count = 2, hf_noise_content = 2,\n                  sensitive_analog = 5, maintenance_ease = 3)\nmesh_scores <- c(panel_count = 5, hf_noise_content = 5,\n                  sensitive_analog = 3, maintenance_ease = 4)\n\nstar_total <- sum(weights * star_scores)\nmesh_total <- sum(weights * mesh_scores)\n\ncat(\"Weighted decision matrix (1 = poor fit, 5 = excellent fit):\\n\\n\")\nfor (nm in names(weights)) cat(sprintf(\"  %-18s weight = %.0f%%\\n\", nm, weights[nm] * 100))\ncat(sprintf(\"\\nStar (single-point) weighted score: %.2f\\n\", star_total))\ncat(sprintf(\"Mesh (multi-point grid) weighted score: %.2f\\n\", mesh_total))\ncat(sprintf(\"\\n-> Recommendation: %s\\n\",\n            ifelse(mesh_total > star_total, \"MESH / MULTI-POINT GRID\", \"STAR / SINGLE-POINT\")))\n```\n\n**Sanity check:** with 14 interconnected panels and multiple VFDs driving the weighting toward panel count and high-frequency noise content, mesh wins clearly — matching the practitioner default from the guidelines above. Try re-running this with weights shifted heavily toward `sensitive_analog` and `panel_count` dropped to reflect the single-panel food-plant scenario instead (one panel, three simple analog instruments, no VFD): the recommendation flips to star, which is exactly the small-installation default this design task's guidance predicts.\n\n## Design Task 7: Touch Voltage — Why Bonding, Not Earthing, Clears the Fault\n\n### Scenario\n\nA food processing plant's electrical contractor is finishing the panel for a new washdown conveyor motor on a 600 Y/347 V grounded wye system, protected by a 20 A branch breaker. A junior electrician on the crew, working from an older mental model, proposes skipping the dedicated equipment bonding conductor back to the panel and instead driving a ground rod at the motor's base — reasoning that \"it's grounded either way.\" The senior electrician needs to settle this with more than an opinion: a clear, numeric comparison of what actually happens to someone touching that motor's frame during a fault, under each approach.\n\n### Design Guidelines and Rules of Thumb\n\nA ground fault — a live conductor coming into unintended contact with a normally non-current-carrying metal part like a motor frame — is only made safe by one thing happening fast: enough current flowing through the fault to trip the upstream overcurrent protective device (OCPD), removing power from the circuit. How much current flows is governed by nothing more exotic than Ohm's law, applied to the *entire fault current loop*: source, through the fault, back to source. The two ways to complete that loop back to the source — a low-impedance equipment bonding conductor, or the earth itself via driven ground rods — have dramatically different impedances, and that difference is the entire safety case.\n\n$$I_{fault} = \\frac{V_{source}}{Z_{loop}}$$\n\n$$V_{touch} \\approx I_{fault} \\times R_{frame\\text{-}to\\text{-}earth}$$\n\n| Symbol | Description | Unit |\n| :--- | :--- | :--- |\n| $V_{source}$ | Phase-to-ground voltage of the source at the point of the fault | V |\n| $Z_{loop}$ | Total impedance of the complete fault-current loop, source through fault and back | Ω |\n| $I_{fault}$ | Fault current driven through that loop | A |\n| $R_{frame\\text{-}to\\text{-}earth}$ | Resistance between the faulted frame and a remote earth reference point | Ω |\n| $V_{touch}$ | Voltage a person contacting the frame and a remote earth reference would experience | V |\n\n**Rule of thumb:** never treat a driven ground rod as a substitute for an equipment bonding conductor — a rod's job (per Design Task 1) is system grounding and surge dissipation, not fault clearing, and soil resistance is simply too high, and too variable, to reliably drive enough fault current to trip a standard OCPD. This breaks down only in the sense that a driven rod is still a genuinely useful, code-required part of the installation for its *actual* job (voltage stabilization, lightning/static dissipation) — the rule isn't \"rods are useless,\" it's \"rods don't do the bonding conductor's job, so never let one substitute for it.\"\n\n### Worked Example\n\nLive cell — try a different system voltage, breaker rating, or rod resistance and see how the fault current and touch voltage respond.\n\n```{webr-r}\n#| label: touch-voltage-06-05\n## Touch voltage comparison: properly bonded equipment vs. earth-rod-only\nV_phase     <- 347   # V, phase-to-ground voltage, 600Y/347 V system (CEC 600 V class)\nOCPD_rating <- 20     # A, branch breaker\n\n## Case A: properly sized equipment bonding conductor (CEC Table 16 / NEC 250.122)\nZ_loop_bonded    <- 0.35            # ohm, bonding conductor + source transformer impedance\nI_fault_bonded   <- V_phase / Z_loop_bonded\ntrip_threshold_A <- OCPD_rating * 9  # instantaneous trip region, ~8-10x rating\n\n## Case B: no equipment bonding conductor -- relying on driven ground rods only\nR_rod_equipment    <- 25   # ohm, commonly cited single driven-rod resistance\nR_electrode_source <- 25   # ohm, source-side grounding electrode resistance\nZ_loop_rod   <- R_rod_equipment + R_electrode_source\nI_fault_rod  <- V_phase / Z_loop_rod\nV_touch_rod  <- I_fault_rod * R_rod_equipment\n\n## Body current estimate for the rod-only case (dry skin, ~1000 ohm)\nR_body    <- 1000\nI_body_mA <- V_touch_rod / R_body * 1000\n\ncat(\"Case A -- Properly bonded equipment:\\n\")\ncat(sprintf(\"  Fault loop impedance: %.2f ohm\\n\", Z_loop_bonded))\ncat(sprintf(\"  Fault current: %.0f A\\n\", I_fault_bonded))\ncat(sprintf(\"  20 A breaker instantaneous trip region: ~%.0f A\\n\", trip_threshold_A))\ncat(sprintf(\"  -> %s: breaker clears the fault in a few cycles (well under 0.1 s)\\n\\n\",\n            ifelse(I_fault_bonded > trip_threshold_A, \"TRIPS FAST\", \"DOES NOT TRIP FAST\")))\n\ncat(\"Case B -- Earth/driven ground rod only (no bonding conductor):\\n\")\ncat(sprintf(\"  Fault loop impedance: %.0f ohm\\n\", Z_loop_rod))\ncat(sprintf(\"  Fault current: %.2f A\\n\", I_fault_rod))\ncat(sprintf(\"  -> %s: %.2f A never reaches the 20 A breaker's trip threshold\\n\",\n            ifelse(I_fault_rod < OCPD_rating, \"NEVER TRIPS\", \"TRIPS\"), I_fault_rod))\ncat(sprintf(\"  Sustained touch voltage on the equipment frame: %.0f V\\n\", V_touch_rod))\ncat(sprintf(\"  Estimated body current if touched (dry skin, %.0f ohm): %.0f mA\\n\\n\",\n            R_body, I_body_mA))\ncat(\"  -> well above commonly cited let-go/fibrillation risk thresholds (30-50 mA),\\n\")\ncat(\"     and it stays energized indefinitely -- not for a fraction of a second\\n\")\n```\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Fault current for a properly bonded circuit versus one relying only on driven ground rods, against the 20 A breaker's rating and its instantaneous trip threshold. The bonded case clears in a few cycles; the rod-only case never trips at all.](06-05-Bonding-Grounding-EMC_files/figure-html/fig-06-05-touch-voltage-compare-1.png){#fig-06-05-touch-voltage-compare fig-align='center' width=960}\n:::\n:::\n\n\n**Sanity check:** the properly bonded circuit drives nearly 1000 A through the fault — comfortably past the breaker's instantaneous trip region, so the hazard exists only for the fraction of a second it takes the breaker to open. The rod-only circuit drives less than 7 A — not even close to the breaker's continuous rating, let alone its trip threshold — leaving the equipment frame sitting at roughly 173 V relative to true earth, indefinitely, until someone finds the fault some other way (often by getting shocked). In a washdown environment, wet skin and standing water can drop body resistance well below the 1000 Ω used here, making the actual shock current higher still. The magnitude of the touch voltage matters, but the *duration* is what makes the rod-only case genuinely dangerous rather than merely undesirable — this is the numeric core of why CSA C22.2 No. 0.4, CEC Section 10, and NEC Article 250 all require a bonding conductor as the primary fault-clearing path, with the grounding electrode system serving its separate, legitimate purpose alongside it, never in place of it.\n\n<details>\n<summary>Industry connection: documentation discipline in regulated manufacturing</summary>\n\nIn a defense-manufacturing facility operating under Controlled Goods Program documentation discipline, bonding continuity is often verified and logged as part of a scheduled electrical preventive-maintenance record, not just checked once at commissioning — because an auditable record that a bonding path was tested and passed is exactly the kind of traceable evidence an audit expects, and it converts \"we believe this is safe\" into \"here is the test record proving it.\" The touch-voltage math above is the reason that test matters: a visually intact bonding conductor with a failed or corroded termination can silently degrade $Z_{loop}$ toward the rod-only case, with no obvious external sign until a fault actually happens.\n\n</details>\n\n## Summary\n\n\n::: {#tbl-06-05-summary .cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover table-condensed\" style=\"margin-left: auto; margin-right: auto;\">\n<caption>Design task summary: governing relationships and key rules of thumb</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;font-weight: bold;color: white !important;background-color: rgba(74, 134, 199, 1) !important;\"> Design Task </th>\n   <th style=\"text-align:left;font-weight: bold;color: white !important;background-color: rgba(74, 134, 199, 1) !important;\"> Governing Relationship </th>\n   <th style=\"text-align:left;font-weight: bold;color: white !important;background-color: rgba(74, 134, 199, 1) !important;\"> Key Rule of Thumb </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> 1. Grounding/bonding/shielding functions </td>\n   <td style=\"text-align:left;\"> Decision framework: bonding = fault path; system ground = earth reference; functional ground = signal reference; shield = EMI diversion </td>\n   <td style=\"text-align:left;\"> If you can't name which of the four jobs a wire is doing, don't use it for anything yet </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 2. CEC vs. NEC terminology </td>\n   <td style=\"text-align:left;\"> CEC \"bonding conductor\" = NEC \"EGC\"; CEC \"grounding conductor\" = NEC \"GEC\" </td>\n   <td style=\"text-align:left;\"> Mentally substitute \"bonded\" for \"grounded\" first, then re-verify the numeric table value independently </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 3. Bonding conductor sizing </td>\n   <td style=\"text-align:left;\"> $A_{bond} = \\text{Table}(I_{OCPD})$ </td>\n   <td style=\"text-align:left;\"> Round up to the next standard size; re-check any time the OCPD rating changes </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 4. Ground loops and the VFD shield exception </td>\n   <td style=\"text-align:left;\"> Shield: ground ONE end at signal frequencies; 360-deg bond BOTH ends at VFD/high frequency </td>\n   <td style=\"text-align:left;\"> Below ~1 MHz, ground the shield once; at VFD switching frequencies, low-impedance bond both ends </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 5. VFD cabling and bearing currents </td>\n   <td style=\"text-align:left;\"> $V_{bearing} = BVR \\times V_{cm}$ </td>\n   <td style=\"text-align:left;\"> Budget 3-6% of peak common-mode voltage landing on an unmitigated bearing film </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 6. Panel layout: separation and topology </td>\n   <td style=\"text-align:left;\"> Decision framework: separation by wiring class; star vs. mesh by panel count/frequency content </td>\n   <td style=\"text-align:left;\"> Keep 150-300 mm between power and signal runs; default to mesh once VFDs and multiple panels are involved </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 7. Touch voltage: bonding vs. earthing </td>\n   <td style=\"text-align:left;\"> $I_{fault}=V_{source}/Z_{loop}$; $V_{touch} \\approx I_{fault} \\times R_{frame\\text{-}to\\text{-}earth}$ </td>\n   <td style=\"text-align:left;\"> A driven ground rod alone will not clear a fault fast -- only a low-impedance bonding conductor will </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n## Practice Problems\n\n<details>\n<summary>Design Task 1, Problem 1 (plug-in): classify the conductor</summary>\n\nA panel has four conductors, each labeled only \"GND\" by the original installer: (a) a 10 AWG wire bonding the panel enclosure to the motor frame it feeds; (b) a drain wire wrapped around a 4-20 mA transmitter cable; (c) a wire from the PLC's 24 VDC power supply's negative terminal to a reference bus; (d) a wire from the service panel's neutral bus to a driven rod outside the building. Classify each by its actual function.\n\n**Solution:** (a) is an **equipment bonding conductor** — it connects a frame to the source for fault clearing. (b) is a **shield** — its job is EMI diversion, and per Design Task 4, it should be grounded at one end only for this low-frequency instrumentation application. (c) is a **functional/signal ground** — a voltage reference for the PLC's electronics, not a fault path. (d) is a **system grounding conductor** — the earth connection for the supply system itself.\n\n</details>\n\n<details>\n<summary>Design Task 1, Problem 2 (design decision): repurposing a spare conductor</summary>\n\nA technician troubleshooting a noisy analog signal finds a spare, unused conductor inside an existing multi-conductor cable that already carries a properly installed equipment bonding conductor. He proposes using that spare conductor as a dedicated signal reference for a new sensor, since \"it's already in the same jacket, going to the same place.\" Good idea?\n\n**Answer:** Not without checking what else shares that cable jacket and where that spare conductor's other end actually terminates. Physical proximity inside the same jacket doesn't establish what function a conductor is safe to serve — if the spare conductor's far end lands on the same terminal as the bonding conductor, or on a bus that also carries other equipment's bonding or return current, using it as a \"clean\" signal reference reintroduces exactly the Design Task 1 problem (a signal reference contaminated by fault-path or return current) even though it looks, at a glance, like a tidy reuse of existing wire. The right move is to trace the conductor's actual termination at both ends and confirm it's isolated from any bonding, load-return, or other equipment's signal path before repurposing it — not to assume \"already in the cable\" means \"safe to use.\"\n\n</details>\n\n<details>\n<summary>Design Task 2, Problem 1 (plug-in): translate the term</summary>\n\nA US-built machine's drawing calls out a \"6 AWG grounding electrode conductor\" running from the machine's main disconnect to a driven rod at the machine's base. What is the correct CEC Section 10 term for this conductor?\n\n**Solution:** This conductor connects the system to earth (a driven rod), not a frame to the source for fault clearing — per the mapping table, the CEC term is **grounding conductor** (not \"bonding conductor,\" which would be the mistranslation a hasty reader might apply since both include the word \"ground\").\n\n</details>\n\n<details>\n<summary>Design Task 2, Problem 2 (design decision): reviewing an NEC-labeled drawing</summary>\n\nAn integrator reviewing an imported machine's US-drawn schematic sees a note stating the machine's frame is \"grounded to the panel via a 10 AWG conductor\" with no further detail, and initially flags this as a compliance gap because CEC Section 10 requires \"bonding,\" not \"grounding,\" of equipment frames. Is the flag justified?\n\n**Answer:** Not as written — this is exactly the terminology trap Design Task 2 exists to catch. The NEC drawing's use of \"grounded\" here almost certainly describes the same fault-current-path function CEC calls \"bonded\" (a frame connected to the panel for fault clearing), not a literal earth connection — historically, NEC documentation used \"grounded\" as a loose umbrella term for both functions. The correct response isn't to flag a gap, it's to verify the conductor's actual function (does it terminate at the frame and route back to the source, or does it go to a driven electrode?) and, once confirmed as the fault-current path, independently check its size against CEC Table 16 rather than either accepting or rejecting the drawing based on word choice alone.\n\n</details>\n\n<details>\n<summary>Design Task 3, Problem 1 (plug-in): size a bonding conductor</summary>\n\nUsing the illustrative table from this design task, what minimum copper bonding conductor size is required for a branch circuit protected by a 100 A breaker, regardless of whether the connected motor draws 22 A or 85 A?\n\n**Solution:** Looking up 100 A in the illustrative table gives **8 AWG**, identical for both motors — the bonding conductor size is a function of the 100 A OCPD rating alone, not of either motor's actual current draw.\n\n</details>\n\n<details>\n<summary>Design Task 3, Problem 2 (design decision): sizing to the motor instead of the OCPD</summary>\n\nA contractor, trying to save copper on a large job, proposes sizing every bonding conductor to each motor's nameplate FLA rather than to its branch circuit's OCPD rating, arguing the bonding conductor \"will never see more current than the load it protects, until a fault happens — and then the smaller wire will still carry it briefly.\" Evaluate this proposal.\n\n**Answer:** Reject it. The entire point of the OCPD-based sizing table is that the bonding conductor's job happens specifically *during* that fault — its size has to be adequate to carry the let-through fault current at low impedance long enough for the OCPD to clear, and that fault current is governed by the OCPD's rating and the system's fault-current-carrying capacity, not by the motor's normal running current. A bonding conductor sized to a small motor's FLA on a branch protected by a much larger OCPD (sized, per code, with headroom for motor starting current) would be undersized for the very fault event it exists to handle — exactly the failure mode this design task's worked example was built to make visible. The copper savings are real but the risk they create is not an acceptable trade.\n\n</details>\n\n<details>\n<summary>Design Task 4, Problem 1 (plug-in): recompute the ground loop current</summary>\n\nA 40 m instrument cable has a total shield resistance of 1.6 Ω. A nearby VFD's fault event momentarily raises the local ground potential by 2.4 V. If the shield were (incorrectly) grounded at both ends, what circulating current would flow?\n\n**Solution:**\n\n$$I_{loop} = \\frac{2.4\\ \\text{V}}{1.6\\ \\Omega} = 1.5\\ \\text{A}$$\n\nA substantial circulating current — reinforcing why the one-end rule matters even more on cables running near VFD-generated ground disturbances.\n\n</details>\n\n<details>\n<summary>Design Task 4, Problem 2 (design decision): \"extra safe\" double-grounding</summary>\n\nA maintenance technician troubleshooting a noisy 4-20 mA signal near a VFD decides to ground the instrument cable shield at both ends, reasoning that more ground connections must reduce noise. Evaluate this fix.\n\n**Answer:** This is very likely to make the noise worse, not better — it's precisely the low-frequency ground-loop scenario this design task's guidance warns against. Grounding the shield at both ends near a VFD, which is actively creating ground potential disturbances through its switching and any fault or leakage current, creates exactly the closed loop needed for a circulating shield current to couple noise into the signal pair. The correct troubleshooting steps are: confirm the shield is grounded at one end only; check separation distance from the VFD cable and power wiring per Design Task 6; and, if noise persists, investigate whether the VFD cable itself has adequate 360° bonding (Design Task 4's other worked example) rather than \"fixing\" the instrument cable's grounding in the wrong direction.\n\n</details>\n\n<details>\n<summary>Design Task 5, Problem 1 (plug-in): recompute the bearing voltage</summary>\n\nA 460 V VFD-fed motor has a DC bus of 1.35 x 460 V = 621 V. Using a BVR of 5%, and a peak common-mode voltage of half the DC bus, estimate the bearing voltage.\n\n**Solution:**\n\n$$V_{cm} = 621/2 = 310.5\\ \\text{V} \\qquad V_{bearing} = 0.05 \\times 310.5 = 15.5\\ \\text{V}$$\n\nComfortably above a representative few-volt-to-low-tens-of-volts film breakdown threshold — this motor is a bearing-current risk without mitigation.\n\n</details>\n\n<details>\n<summary>Design Task 5, Problem 2 (design decision): choosing a retrofit mitigation</summary>\n\nA plant with a dozen already-installed VFD-fed conveyor motors, several now showing early bearing fluting, needs to choose a mitigation strategy. Options: (a) replace all VFD cabling with symmetrical shielded cable and proper 360° bonding on every drive; (b) install common-mode chokes on each drive's output; (c) retrofit shaft grounding rings on the affected motors. Which would you recommend as the first step, and why?\n\n**Answer:** For an already-operating plant with existing (and possibly adequately performing) cabling, shaft grounding rings (option c) are usually the fastest, lowest-disruption first step — they can typically be installed on an existing motor during a routine maintenance window without re-pulling cable or reworking the drive's output wiring, and they directly address the bearing damage mechanism by giving discharge current a path that bypasses the bearing. Re-cabling every drive (option a) is the most thorough long-term fix, since it also improves the plant's overall EMI performance (radiated noise, susceptibility of nearby equipment), but it's expensive and disruptive to retrofit across a dozen already-installed drives, and is better justified as new-installation standard practice than an emergency retrofit. Common-mode chokes (option b) are a reasonable middle option, particularly for drives where cabling is hard to access, but they add cost per drive and address the voltage at the source rather than the specific bearing discharge path — a plant might reasonably combine (c) now with (a) specified as the standard for all future installations.\n\n</details>\n\n<details>\n<summary>Design Task 6, Problem 1 (plug-in): check a separation distance</summary>\n\nA cable tray runs a 4-20 mA level signal cable parallel to a 480 V power feeder for 8 m, with 100 mm of vertical separation between them. Does this satisfy the illustrative Level 1 separation guidance from this design task?\n\n**Solution:** No — the illustrative guidance calls for at least 300 mm (12 in) of separation for sensitive analog wiring running parallel to power circuits over 20 A, and this installation provides only 100 mm over a meaningful 8 m parallel run. The fix is either increasing physical separation to at least 300 mm, moving one of the two cables to a separate tray, or routing the crossing sections at 90° wherever the parallel run can be broken up.\n\n</details>\n\n<details>\n<summary>Design Task 6, Problem 2 (design decision): topology for a single washdown panel</summary>\n\nThe food-plant conveyor skid from this design task's scenario — one washdown panel, three analog instruments, no VFD — needs a grounding topology decision. Star or mesh, and why?\n\n**Answer:** Star (single-point). With a single panel, no interconnection to other panels, no VFD or other significant high-frequency noise source present, and three sensitive analog instruments as the dominant wiring type, this scenario sits at the opposite end of the decision framework from the automotive body-shop example: low panel count, low high-frequency noise content, high analog sensitivity. A mesh topology would add installation complexity (multiple bonding paths between points that don't need it) with no corresponding benefit, since there's no multi-panel high-frequency performance problem to solve. Running the weighted decision matrix from the worked example with weights shifted toward `sensitive_analog` and `panel_count` set near its minimum score for mesh confirms this conclusion numerically.\n\n</details>\n\n<details>\n<summary>Design Task 7, Problem 1 (plug-in): recompute with a different rod resistance</summary>\n\nUsing the same 347 V system and 20 A breaker, but with a poorly performing single ground rod tested at 60 Ω (soil-resistance dependent, well above the code's typical 25 Ω supplemental-electrode threshold) as the equipment-side path, and the same 25 Ω source electrode, find the fault current and touch voltage if no bonding conductor is present.\n\n**Solution:**\n\n$$Z_{loop} = 60 + 25 = 85\\ \\Omega \\qquad I_{fault} = 347/85 = 4.08\\ \\text{A}$$\n$$V_{touch} = 4.08 \\times 60 = 244.7\\ \\text{V}$$\n\nWorse than the worked example's 25 Ω case in both respects — even lower fault current (further from tripping the breaker) and a higher sustained touch voltage. Poor soil conditions make the rod-only approach even more dangerous, not less.\n\n</details>\n\n<details>\n<summary>Design Task 7, Problem 2 (design decision): is the ground rod pointless, then?</summary>\n\nGiven how badly the rod-only approach performs at clearing a fault, is there any point installing a driven ground rod at all, if a proper equipment bonding conductor is already in place?\n\n**Answer:** Yes — the rod still does real, necessary work, just not the fault-clearing job. A grounding electrode (the rod) stabilizes the electrical system's voltage relative to earth, gives lightning and static discharge a path to dissipate that doesn't route through equipment or people, and is required by CEC Section 10 and NEC Article 250 as part of a complete grounding and bonding system — alongside, not instead of, the bonding conductor. The lesson of this design task isn't \"rods are worthless,\" it's \"a rod is not a substitute for a bonding conductor,\" which is a different and more precise statement. A correctly designed installation has both: an equipment bonding conductor doing the fast, low-impedance fault-clearing job, and a grounding electrode system doing the separate job of referencing the whole installation to earth.\n\n</details>\n\n## Open-Ended Design Scenario\n\n<details>\n<summary>Capstone: bonding, grounding, and EMC package for a poultry processing intake and conveying cell</summary>\n\nA poultry processing plant is installing a new intake and conveying cell. Product arrives on a VFD-driven infeed conveyor (600 V, 15 hp motor, symmetrical shielded cable specified from the drive to the motor), passes a check-weigh station with a load cell feeding a 4-20 mA signal to the line PLC, and discharges onto a decline takeaway conveyor with its own VFD. The whole cell sits inside a single washdown-rated control panel enclosure, fed from the plant's 600 Y/347 V distribution system through a 100 A branch breaker, and the panel is physically adjacent to two other existing washdown panels on the same line, sharing a common cable tray.\n\nUsing the methods developed in this chapter:\n\n1. Using Design Task 1's framework, classify the four conductor types you'd expect to find in this cell (equipment bonding, system grounding, functional/signal ground, shield), and identify one specific conductor in the scenario above that belongs to each category.\n2. If any of this cell's equipment arrives with US-drawn (NEC-labeled) documentation, apply Design Task 2's translation procedure to confirm the bonding scheme satisfies CEC Section 10 as adopted by the Ontario Electrical Safety Code.\n3. Using Design Task 3's method, determine the minimum bonding conductor size for the 100 A branch circuit feeding this panel, and explain why the two VFD motors' differing FLA ratings don't change that answer.\n4. Using Design Task 4's guidance, specify the shielding practice for both the load cell's 4-20 mA cable and the two VFDs' motor cables, and explain why they're different.\n5. Using Design Task 5's guidance, specify what cabling and bonding practice protects both motors' bearings from common-mode current damage, and identify at least one additional mitigation worth specifying given that this plant already has other VFD-driven equipment on the same structural steel and tray system.\n6. Using Design Task 6's guidance, decide on a separation distance plan for the load cell's signal cable against the two VFDs' output cables in the shared tray, and decide whether this panel and its two washdown neighbours should use a star or mesh grounding topology, defending the choice with the decision matrix approach from the worked example.\n7. Using Design Task 7's method, calculate the fault current and touch voltage this panel's equipment would present under a phase-to-ground fault, assuming the bonding conductor from item 3 is correctly installed — and separately, what would happen if a technician years from now removed that bonding conductor during a panel modification and never reconnected it, relying on the panel's structural mounting to \"probably\" provide a fault path.\n\nThere's no single correct numeric answer here — different reasonable assumptions about cable lengths, fault loop impedance, and specific equipment will lead to different (defensible) results. The goal is a documented bonding, grounding, and EMC package, in the style of this chapter's worked examples, that a plant engineer could hand to an electrical contractor and a CFIA-facing food-safety reviewer alike and have both sign off on it.\n\n</details>\n",
    "supporting": [
      "06-05-Bonding-Grounding-EMC_files\\figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"site_libs/jquery-3.6.0/jquery-3.6.0.min.js\"></script>\n<script src=\"site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}