{
  "hash": "cbb53dcc2ddf700fc039c1c5858be7dd",
  "result": {
    "engine": "knitr",
    "markdown": "## Design for Machining {#chap-machining}\n\n\n\n### Learning Objectives {#sec-objectives-07}\n\nBy the end of this chapter, you will be able to:\n\n1. **Apply** Design for Machining (DFM) principles to reduce manufacturing costs\n2. **Calculate** spindle speed and machining time for turning operations\n3. **Identify** common design features that make parts difficult to machine\n4. **Implement** guidelines for tolerances, hole sizes, and feature accessibility\n5. **Evaluate** machining designs for automotive, food, and defense industry applications\n\n::: {.callout-think}\n**Before You Read:** Why do you think DFM is particularly important in high-volume industries like automotive? Can you think of a part in your daily life that might have been designed poorly for machining?\n:::\n\n### Introduction to Design for Machining {#sec-machining-intro}\n\nDesign for Machining (DFM) helps engineers create parts that are easy and cost-effective to machine. DFM principles reduce manufacturing costs, improve quality, and speed up production time. In this chapter, we'll explore the fundamentals of DFM, with real-world examples from the automotive, food, and defense industries.\n\nFor a visual introduction to DFM in machining, check out these helpful YouTube videos: [Top Design Tips & Manufacturing Processes for Mechanical Engineers | DFM Guide](https://www.youtube.com/watch?v=sq3Ht-ivG5U) and [Only Real Mechanical Engineers Can Spot These Design Mistakes | CNC Machining](https://www.youtube.com/watch?v=rauL_J048sI).\n\n\n<div style=\"position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%;\">\n  <iframe\n    style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%;\"\n    src=\"https://www.youtube.com/embed/sq3Ht-ivG5U\"\n    title=\"Top Design Tips & Manufacturing Processes for Mechanical Engineers | DFM Guide\"\n    frameborder=\"0\"\n    allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\"\n    referrerpolicy=\"strict-origin-when-cross-origin\"\n    allowfullscreen>\n  </iframe>\n</div>\n\n\n<div style=\"position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%;\">\n  <iframe\n    style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%;\"\n    src=\"https://www.youtube.com/embed/rauL_J048sI\"\n    title=\"Only Real Mechanical Engineers Can Spot These Design Mistakes | CNC Machining\"\n    frameborder=\"0\"\n    allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\"\n    referrerpolicy=\"strict-origin-when-cross-origin\"\n    allowfullscreen>\n  </iframe>\n</div>\n\n---\n\n### DFM Guidelines for Machined Parts {#sec-machining-guidelines}\n\nBefore diving into calculations, let's establish the fundamental design guidelines that make parts easier and cheaper to machine.\n\n#### Internal Corners and Fillets\n\nSharp internal corners are impossible to machine with rotating cutters. Always specify **fillet radii** at internal corners.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Internal corners require fillet radii matching available tool sizes.](03-05-Machining_files/figure-html/fig-internal-corners-1.png){#fig-internal-corners fig-align='center' width=960}\n:::\n:::\n\n\n**Guideline:** Internal fillet radius should be at least **1.5× the tool radius** to allow the tool to move smoothly without dwelling in corners.\n\n#### Standard Hole Sizes\n\nSpecifying standard drill sizes reduces tooling costs and setup time.\n\n| Preferred Hole Diameters (mm) |\n|:------------------------------|\n| 3, 4, 5, 6, 8, 10, 12, 14, 16, 18, 20, 22, 25, 28, 30 |\n\n::: {.callout-check}\n**Quick Check:** A designer specifies a 7.3 mm diameter hole. Why might this cause problems in manufacturing?\n:::\n\n#### Depth Limitations\n\n**Hole depth:** Standard drills can reliably produce holes up to **3× diameter** deep. Deeper holes require special tooling.\n\n**Pocket depth:** Avoid pockets deeper than **4× the tool diameter** to prevent tool deflection.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Hole and pocket depth guidelines relative to tool diameter.](03-05-Machining_files/figure-html/fig-depth-guidelines-1.png){#fig-depth-guidelines fig-align='center' width=960}\n:::\n:::\n\n\n#### Wall Thickness\n\nThin walls deflect under cutting forces, causing chatter and poor surface finish. Minimum wall thickness depends on material and wall height.\n\n| Material | Minimum Wall Thickness |\n|:---------|:-----------------------|\n| Steel | 3 mm or 0.1× height, whichever is greater |\n| Aluminum | 2 mm or 0.08× height |\n| Plastic | 1.5 mm |\n\n::: {.callout-industry}\n**Automotive Application:** Engine block designers must balance thermal efficiency (thin walls for better cooling) against machinability (thick enough walls to resist cutting forces during cylinder boring).\n:::\n\n---\n\n### Theory and Calculations {#sec-machining-theory}\n\nDesign for Machining involves considering the capabilities and limitations of machining processes like milling, turning, and drilling during the design phase. Key principles include minimizing material removal, avoiding deep pockets, using standard hole sizes, and ensuring adequate tolerances.\n\nMathematically, one core aspect is calculating spindle speed and feed rates to optimize machining. The spindle speed $N$ (in RPM) is given by:\n\n$$N = \\frac{1000 \\times v}{\\pi \\times D}$$\n\nwhere $v$ is the cutting speed (m/min), and $D$ is the tool diameter (mm).\n\nMachining time $T$ for a turning operation can be:\n\n$$T = \\frac{L}{f \\times N}$$\n\nwhere $L$ is the length of cut (mm), and $f$ is the feed rate (mm/rev).\n\nLet's use R to perform a detailed example calculation. Suppose we're machining a shaft in the automotive industry with $v = 150$ m/min, $D = 20$ mm, $L = 100$ mm, and $f = 0.2$ mm/rev.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Define parameters\nv <- 150  ## cutting speed in m/min\nD <- 20   ## diameter in mm\nL <- 100  ## length in mm\nf <- 0.2  ## feed in mm/rev\n\n## Calculate spindle speed N\nN <- (1000 * v) / (pi * D)\nN\n\n## Calculate machining time T\nT <- L / (f * N)\nT  ## in minutes\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2387.324\n[1] 0.2094395\n```\n\n\n:::\n:::\n\n\nThis shows a spindle speed of approximately 2387.32 RPM and machining time of about 0.209 minutes. Adjust these parameters in your own code to see how they affect the results!\n\nIn industries like defense, where precision is critical, tolerances must be tight but achievable. Overly tight tolerances increase costs exponentially.\n\n#### Challenge Questions\n\n1. Derive the formula for machining time if the feed rate changes with material hardness.\n2. How would you adjust the cutting speed for a food industry application using stainless steel?\n\n### Hands-on Examples\n\nNow, let's apply DFM to specific industries using R for analysis and visualization.\n\n#### Automotive Industry\n\nIn automotive, DFM is used for engine components like pistons and crankshafts. Using the built-in `mtcars` dataset, we can analyze how design parameters (e.g., horsepower and weight) relate to machined parts' performance. Imagine horsepower as a proxy for engine complexity, which affects machining time.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(mtcars)\nggplot(mtcars, aes(x = wt, y = hp)) +\n  geom_point(color = \"blue\") +\n  theme_minimal() +\n  labs(title = \"Horsepower vs Vehicle Weight\",\n       x = \"Weight (1000 lbs)\",\n       y = \"Horsepower\") +\n  scale_color_viridis_d()  ## Colorblind-friendly\n```\n\n::: {.cell-output-display}\n![Horsepower vs Weight in Automotive Designs](03-05-Machining_files/figure-html/plot-auto-1.png){width=672}\n:::\n:::\n\n\nThis scatter plot shows that heavier vehicles often require more powerful (and thus more complex to machine) engines.\n\n\n\n\n#### Food Industry\n\nIn the food industry, machined parts include conveyor rollers and mixing blades, often in food-grade stainless steel. Let's simulate data for machining costs vs. part complexity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\ncomplexity <- rnorm(50, mean = 5, sd = 2)\ncost <- 10 * complexity + rnorm(50, mean = 0, sd = 5)\nfood_data <- data.frame(complexity, cost)\n\nggplot(food_data, aes(x = complexity, y = cost)) +\n  geom_point(color = \"green\") +\n  geom_smooth(method = \"lm\", formula = y ~ x, color = \"darkgreen\") +\n  theme_minimal() +\n  labs(title = \"Machining Cost vs Part Complexity\",\n       x = \"Complexity Score\",\n       y = \"Cost ($)\") +\n  scale_color_viridis_d()\n```\n\n::: {.cell-output-display}\n![Simulated Machining Cost vs Complexity in Food Industry](03-05-Machining_files/figure-html/plot-food-1.png){width=672}\n:::\n:::\n\n\nHigher complexity leads to higher costs—DFM aims to minimize this.\n\n\n\n\n#### Defense Industry\n\nFor defense, parts like aircraft fittings require high precision. Let's create an interactive plot of tolerance distributions using simulated data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Simulated tolerance data\nset.seed(123)\ntolerances <- rnorm(100, mean = 0, sd = 0.01)\ndefense_data <- data.frame(tolerances)\n\np <- ggplot(defense_data, aes(x = tolerances)) +\n  geom_histogram(bins = 20, fill = \"red\", color = \"black\") +\n  theme_minimal() +\n  labs(title = \"Distribution of Machining Tolerances\",\n       x = \"Tolerance Deviation (mm)\",\n       y = \"Frequency\") +\n  scale_fill_viridis_d()\n\nif (knitr::is_html_output(excludes = \"epub\")) {\n  plotly::ggplotly(p)\n} else {\n  p\n}\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-1d5df3d80f5735caaf13\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-1d5df3d80f5735caaf13\">{\"x\":{\"data\":[{\"orientation\":\"v\",\"width\":[0.0023665799308723104,0.0023665799308723104,0.0023665799308723104,0.0023665799308723104,0.0023665799308723104,0.0023665799308723104,0.0023665799308723104,0.0023665799308723104,0.0023665799308723104,0.0023665799308723104,0.0023665799308723104,0.0023665799308723069,0.0023665799308723104,0.0023665799308723104,0.0023665799308723104,0.0023665799308723104,0.0023665799308723104,0.0023665799308723104,0.0023665799308723104,0.0023665799308723104],\"base\":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],\"x\":[-0.023091688756408126,-0.020725108825535816,-0.018358528894663505,-0.015991948963791195,-0.013625369032918886,-0.011258789102046578,-0.0088922091711742673,-0.006525629240301957,-0.0041590493094296466,-0.0017924693785573362,0.00057411055231497421,0.0029406904831872829,0.0053072704140595915,0.0076738503449319019,0.010040430275804212,0.012407010206676523,0.014773590137548833,0.017140170068421143,0.019506749999293454,0.021873329930165764],\"y\":[1,1,0,2,2,8,0,10,11,11,9,10,9,6,6,4,5,2,1,2],\"text\":[\"count:  1<br />tolerances: -0.0230916888\",\"count:  1<br />tolerances: -0.0207251088\",\"count:  0<br />tolerances: -0.0183585289\",\"count:  2<br />tolerances: -0.0159919490\",\"count:  2<br />tolerances: -0.0136253690\",\"count:  8<br />tolerances: -0.0112587891\",\"count:  0<br />tolerances: -0.0088922092\",\"count: 10<br />tolerances: -0.0065256292\",\"count: 11<br />tolerances: -0.0041590493\",\"count: 11<br />tolerances: -0.0017924694\",\"count:  9<br />tolerances:  0.0005741106\",\"count: 10<br />tolerances:  0.0029406905\",\"count:  9<br />tolerances:  0.0053072704\",\"count:  6<br />tolerances:  0.0076738503\",\"count:  6<br />tolerances:  0.0100404303\",\"count:  4<br />tolerances:  0.0124070102\",\"count:  5<br />tolerances:  0.0147735901\",\"count:  2<br />tolerances:  0.0171401701\",\"count:  1<br />tolerances:  0.0195067500\",\"count:  2<br />tolerances:  0.0218733299\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(255,0,0,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,0,0,1)\"}},\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":50.776255707762552,\"r\":10.228310502283104,\"b\":52.164383561643838,\"l\":43.981735159817347},\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":20.456621004566209},\"title\":{\"text\":\"Distribution of Machining Tolerances\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":24.547945205479447},\"x\":0,\"xref\":\"paper\"},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-0.026641558652716592,0.02542319982647423],\"tickmode\":\"array\",\"ticktext\":[\"-0.02\",\"-0.01\",\"0.00\",\"0.01\",\"0.02\"],\"tickvals\":[-0.019999999999999997,-0.0099999999999999985,-3.4694469519536142e-18,0.010000000000000002,0.020000000000000004],\"categoryorder\":\"array\",\"categoryarray\":[\"-0.02\",\"-0.01\",\"0.00\",\"0.01\",\"0.02\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":5.1141552511415522,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":16.365296803652971},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.92984640929846418,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"Tolerance Deviation (mm)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":20.456621004566209}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-0.55000000000000004,11.550000000000001],\"tickmode\":\"array\",\"ticktext\":[\"0\",\"3\",\"6\",\"9\"],\"tickvals\":[0,3,6.0000000000000009,9],\"categoryorder\":\"array\",\"categoryarray\":[\"0\",\"3\",\"6\",\"9\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":5.1141552511415522,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":16.365296803652971},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.92984640929846418,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"Frequency\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":20.456621004566209}},\"hoverformat\":\".2f\"},\"shapes\":[],\"showlegend\":false,\"legend\":{\"bgcolor\":null,\"bordercolor\":null,\"borderwidth\":0,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":16.365296803652971},\"title\":{\"text\":\"\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":20.456621004566209}}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"343034b13099\":{\"x\":{},\"type\":\"bar\"}},\"cur_data\":\"343034b13099\",\"visdat\":{\"343034b13099\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\nThis interactive histogram allows you to hover over bins to see details—useful for understanding variability in defense applications.\n\n\n\n\n#### Challenge Questions\n\n1. Modify the automotive plot to filter for cars with more than 6 cylinders. What insights do you gain?\n2. In the food industry simulation, add a variable for material type and replot. How does it affect costs?\n3. For the defense plot, change the standard deviation to 0.005. How does tighter tolerance impact the distribution?\n\n### Interactive Exercises\n\nTry modifying the R code chunks above! For example, change the parameters in the machining calculation and rerun. Think critically: How would DFM principles alter a design with sharp internal corners in an automotive bracket?\n\n---\n\n### Tolerance and Surface Finish {#sec-machining-tolerances}\n\nTolerances and surface finish specifications have a dramatic impact on machining cost. The relationship is exponential, not linear.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Relative machining cost increases exponentially as tolerances tighten.](03-05-Machining_files/figure-html/fig-tolerance-cost-1.png){#fig-tolerance-cost fig-align='center' width=864}\n:::\n:::\n\n\n**Design Guideline:** Only specify tight tolerances where functionally necessary. A ±0.1 mm tolerance costs approximately 2.5× more than ±0.5 mm, while ±0.01 mm costs 15× more.\n\n::: {.callout-discussion}\n**Group Discussion:** Review a mechanical assembly drawing. Identify which dimensions truly require tight tolerances (fits, sealing surfaces) and which could be relaxed without affecting function.\n:::\n\n---\n\n### Common DFM Mistakes to Avoid {#sec-machining-mistakes}\n\n| Mistake | Problem | Solution |\n|:--------|:--------|:---------|\n| Sharp internal corners | Tool cannot reach; requires EDM | Add fillet radius ≥ tool radius |\n| Non-standard hole sizes | Requires custom drills; added setup | Use standard drill sizes |\n| Deep narrow pockets | Tool deflection; poor finish | Limit depth to 4× tool diameter |\n| Unnecessary tight tolerances | Exponential cost increase | Tolerance only critical features |\n| Thin walls | Chatter; deflection | Maintain minimum wall thickness |\n| Blind holes with flat bottoms | Standard drills leave points | Accept drill point or specify boring |\n| Features on multiple sides | Multiple setups required | Consolidate features to fewer sides |\n\n::: {.callout-think}\n**Design Challenge:** You have a bracket that requires holes on three different faces. How could you redesign it to reduce the number of machining setups?\n:::\n\n---\n\n### Check Your Understanding\n\n::: {.question}\n**Question 1:** What is the formula for spindle speed?\n\na) $N = \\frac{\\pi D}{1000 v}$\nb) $N = \\frac{1000 v}{\\pi D}$\nc) $N = \\pi D v$\n:::\n\n::: {.answer}\n**Answer: b**\n\nThe spindle speed formula is $N = \\frac{1000 v}{\\pi D}$ where $v$ is cutting speed in m/min and $D$ is diameter in mm.\n:::\n\n::: {.question}\n**Question 2:** In which industry might hygiene requirements most affect material choice for machining?\n\na) Automotive\nb) Food\nc) Defense\n:::\n\n::: {.answer}\n**Answer: b) Food**\n\nFood processing equipment must use materials like 316 stainless steel that resist corrosion, can be sanitized, and won't contaminate products.\n:::\n\n::: {.question}\n**Question 3:** True or False: Tighter tolerances always reduce manufacturing costs.\n:::\n\n::: {.answer}\n**Answer: False**\n\nTighter tolerances dramatically *increase* manufacturing costs. Each order of magnitude improvement in tolerance can cost 3-5× more.\n:::\n\n---\n\n### Practice Problems {#sec-machining-practice}\n\n::: {.question}\n**Problem 1:** Calculate the spindle speed and machining time for turning a 50 mm diameter shaft, 200 mm long. The material is aluminum with a recommended cutting speed of 300 m/min. Use a feed rate of 0.3 mm/rev.\n:::\n\n::: {.answer}\n**Solution:**\n\n**Spindle Speed:**\n$$N = \\frac{1000 \\times v}{\\pi \\times D} = \\frac{1000 \\times 300}{\\pi \\times 50} = \\frac{300000}{157.08} = 1910 \\text{ RPM}$$\n\n**Machining Time:**\n$$T = \\frac{L}{f \\times N} = \\frac{200}{0.3 \\times 1910} = \\frac{200}{573} = 0.35 \\text{ minutes} = 21 \\text{ seconds}$$\n:::\n\n::: {.question}\n**Problem 2:** A designer specifies internal corners with 1 mm fillet radius in a pocket. The smallest available end mill has an 8 mm diameter (4 mm radius). Will this design work? What should the designer change?\n:::\n\n::: {.answer}\n**Solution:**\n\nNo, this design will not work. The 8 mm end mill has a 4 mm radius, so the minimum internal fillet it can produce is 4 mm—not 1 mm.\n\n**Recommendations:**\n1. Increase the internal fillet radius to at least 4 mm (preferably 6 mm for smoother tool motion)\n2. Or, specify that corners be finished with EDM (electrical discharge machining) at significant additional cost\n3. Or, redesign to eliminate the pocket entirely\n:::\n\n::: {.question}\n**Problem 3:** A part requires the following tolerances. Estimate the relative machining cost if the baseline (±0.5 mm) costs $10 per part.\n\n- Feature A: ±0.5 mm\n- Feature B: ±0.1 mm\n- Feature C: ±0.025 mm\n:::\n\n::: {.answer}\n**Solution:**\n\nUsing the tolerance-cost relationship:\n- Feature A (±0.5 mm): 1× baseline = $10\n- Feature B (±0.1 mm): ~2.5× baseline = $25\n- Feature C (±0.025 mm): ~7× baseline = $70\n\n**Total estimated machining cost: $105 per part**\n\nNote: If Feature C could be relaxed to ±0.1 mm, the total would drop to $45—a 57% cost reduction.\n:::\n\n---\n\n### Key Takeaways {#sec-machining-takeaways}\n\n1. **Design with standard tools in mind:** Use standard drill sizes, avoid sharp internal corners, and limit feature depths to standard tool capabilities.\n\n2. **Tolerances drive cost:** The relationship between tolerance and cost is exponential. Only specify tight tolerances where functionally necessary.\n\n3. **Minimize setups:** Design parts so all features can be machined from as few orientations as possible. Each setup adds time and potential alignment error.\n\n4. **Understand spindle speed and feed:** The formulas $N = \\frac{1000v}{\\pi D}$ and $T = \\frac{L}{fN}$ are fundamental to predicting machining time and cost.\n\n5. **Material matters:** Material selection affects cutting speeds, tool wear, and achievable tolerances. Harder materials require slower speeds and cost more to machine.\n\n---\n\n### Further Resources {#sec-machining-resources}\n\n**Videos:**\n\n<div style=\"position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%;\">\n  <iframe\n    style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%;\"\n    src=\"https://www.youtube.com/embed/sq3Ht-ivG5U\"\n    title=\"DFM Guide for Mechanical Engineers\"\n    frameborder=\"0\"\n    allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\"\n    referrerpolicy=\"strict-origin-when-cross-origin\"\n    allowfullscreen>\n  </iframe>\n</div>\n\n**Reference Tables:**\n- [Machinery's Handbook](https://www.industrialpress.com/machinerys-handbook/) - Comprehensive reference for speeds, feeds, and tolerances\n- [Cutting Speed Charts by Material](https://www.sandvik.coromant.com/) - Sandvik Coromant technical resources\n\n**Reading:**\n- Design for Manufacturability Handbook, James G. Bralla\n- Fundamentals of Modern Manufacturing, Mikell P. Groover",
    "supporting": [
      "03-05-Machining_files\\figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/htmltools-fill-0.5.9/fill.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"site_libs/plotly-binding-4.12.1/plotly.js\"></script>\n<script src=\"site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"site_libs/crosstalk-1.2.2/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/crosstalk-1.2.2/js/crosstalk.min.js\"></script>\n<link href=\"site_libs/plotly-htmlwidgets-css-2.25.2/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/plotly-main-2.25.2/plotly-latest.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}